### PR TITLE
Deprecating: IO package

### PR DESCRIPTION
**Pull request by mts299**
# Deprecation
removing pydarn/io package from pydarn and moving to pyDARNio. 

## Reason
out of the scope of pyDARN

### test
make sure it still installs, may need to install pyDARNio via github to see if works with it. 

Please note this removal if we make pydarnio a sub repo it needs to be released and then I can add its feature into pyDARN to make the switch less painful as some people have brought up. #70

### CODE REVIEW

**Comment by carleyjmartin** [comment]
Just tried installing, installed this branch and the pydarnio develop branch. And tried to make some acf plots. 
Getting hung up on line 15 of acf.py, I think it's still trying to read in DmapArray from pydarn.
```
from pydarn import (dmap2dict, DmapArray, DmapScalar,
                    plot_exceptions, SuperDARNRadars,
                    standard_warning_format, time2datetime,
                    check_data_type)
```
Error: `ImportError: cannot import name 'DmapArray' from 'pydarn'`

**Comment by mts299** [comment]
@carleyjmartin you can now test the PR :)

**Review by carleyjmartin — COMMENTED** [review]
All looks good to me. 

Install was fine, except I got the hdw error again... I've got that on three different installs on three different branches today - so it could be a problem my end? I installed using:
`pip install git+https://github.com/superdarn/pydarn@DEP/io_removal`

Otherwise: tested making a summary plot and an acf, no issues there. 
```
import matplotlib.pyplot as plt 
import pydarn
import pydarnio
import logging

#Load in dmap file
file = "/Users/carley/Documents/data/20131031.2201.00.sas.fitacf"
SDarn_read = pydarnio.SDarnRead(file)
fitacf_data = SDarn_read.read_fitacf()
#Plot FOV and show
#a = pydarn.RTP.plot_range_time(fitacf_data, beam_num=5)
a = pydarn.RTP.plot_summary(fitacf_data, beam_num=5)
plt.show()
``` 
and 
```
import pydarn
import pydarnio
import matplotlib.pyplot as plt 
from datetime import datetime

reader = pydarnio.SDarnRead("/Users/carley/Documents/data/20140105.1200.03.cly.rawacf")
data = reader.read_rawacf()
pydarn.ACF.plot_acfs(data, beam_num=15, gate_num=16,
                start_time=datetime(2014, 1, 5, 13, 30))
plt.show()
```

Happy to approve if the install thing is my own doing.

**Comment by mts299** [comment]
What's the hardware error?

**Comment by carleyjmartin** [comment]
The missing dcn hardware file after a new install.

**Comment by mts299** [comment]
@carleyjmartin probably can merge this if the hardware issue happens on other branches too and then we can figure it out.

**Comment by carleyjmartin** [comment]
Sorry, only just seen you comment. Merging now!

**Pull request merged**
