### PR TITLE
EHN: RTP Start Time Rounding Options

### PR DESCRIPTION
**Pull request by carleyjmartin**
# Scope 

This PR aims to give more flexibility to the rounding of the start time for the RTPs.
Firstly, a keyword option is now given called `round_start`. This value defaults to True which will be a similar behaviour before, it won't break any code backwards, hopefully. When set to False the plot will start exactly from the time given, when set to True or left blank it will round and add white space.
Secondly, the rounding will now occur with the tick interval. So if the tick interval is 10 minutes, it will round to the previous whole 10 minutes, if its 30 mins: to the previous whole 30 minutes, etc. This is done by detecting the tick interval before setting the rounding. This means that the plot will always have a tick label at the start of the xaxis (if True).
This functionality is passed to summary plots via **kwargs from #169 updates.

Issue to close: #167 

In this issue, it discusses about filling in with data the white space and changing the start time in title. As the user is asking for data from a specific time, I'm not sure the time required to do this would be beneficial. I predict it may be a large refactoring rather than a quick fix for something thats relatively minor.

## Approval

**Number of approvals:** Small change, but probably 2 to check for edge cases where it might break?

## Test

**matplotlib version**: 3.4.2
**Note testers: please indicate what version of matplotlib you are using**

```python
import matplotlib.pyplot as plt 
import pydarn

file = "/path/to/fitacf.file"
SDarn_read = pydarn.SuperDARNRead(file)
fitacf_data = SDarn_read.read_fitacf()

# comment as applicable and change round_start
a = pydarn.RTP.plot_range_time(fitacf_data, beam_num=5, round_start=False)
#a = pydarn.RTP.plot_time_series(fitacf_data, beam_num=3, parameter='v', gate=40, round_start=True)
#a = pydarn.RTP.plot_time_series( fitacf_data, start_time=time, beam_num=5, round_start=True, color='red')
#a = pydarn.RTP.plot_summary(fitacf_data, beam_num=2, round_start=True)
plt.show()
```

Example:
`a = pydarn.RTP.plot_range_time(fitacf_data, beam_num=5, round_start=False)`
Screen Shot 2021-07-06 at 1 42 15 PM

`a = pydarn.RTP.plot_range_time(fitacf_data, beam_num=5, round_start=True`
Screen Shot 2021-07-06 at 1 42 35 PM

*Reminder, please check your code is:
  - copyrighted (if applicable)
  - Appropriate disclaimer added
  - Modification line filled in (if applicable)*

### CODE REVIEW

**Comment by mts299** [comment]
Will get to this tomorrow morning :)

**Comment by Devin-Huyghebaert** [comment]
Tried to run with some old test code.

Error:
  File "pydarn_rtp_review_test.py", line 57, in <module>
    pydarn.RTP.plot_range_time(fitacf_data, beam_num=beam_num,round_start=True,ax=ax[1])
  File ".../lib/python3.8/site-packages/pydarn/plotting/rtp.py", line 461, in plot_range_time
    timedelta(minutes=x[0].minute % tick_sep,
ZeroDivisionError: integer division or modulo by zero

`import pydarn
import matplotlib.pyplot as plt
from glob import glob
from collections import deque
import bz2
import datetime

import matplotlib as mpl
mpl.rcParams['figure.figsize'] = 20, 10

#dates
#sas 20200430
#mcm 20161124
#inv 20150929
#hok 20190414
#fhw 20170729

radar_date = ['20200430','20161124','20150929','20190414','20170729']
radar_site = ['sas','mcm','inv','hok','fhw']


#-----

for x in range(len(radar_site)):

    path='data/pydarn_2_test_data/'

    fitacf_data=0

    fitacf_data=deque() 

    date=radar_date[x]
    radar=radar_site[x]

    path=path+radar

    fitacf_files = glob(f'{path}/{date}*{radar}*fitacf.bz2')

    if fitacf_files == []:
        raise Exception('Error: No data for radar {}'.format(radar))

    fitacf_files.sort()

    for fitacf_file in fitacf_files:
        with bz2.open(fitacf_file) as fp:
            fitacf_stream = fp.read()
        fitacf_reader = pydarn.SuperDARNRead(fitacf_stream,True)
        records = fitacf_reader.read_fitacf()
        fitacf_data += records
    print(f'Reading {radar_site[x]} complete...')
    
    #-----
    for beam_num in range(16):
        fig,ax = plt.subplots(2)
        pydarn.RTP.plot_range_time(fitacf_data, beam_num=beam_num,round_start=False,ax=ax[0])
        pydarn.RTP.plot_range_time(fitacf_data, beam_num=beam_num,round_start=True,ax=ax[1])
        plt.show()`

**Comment by carleyjmartin** [comment]
Thanks Devin! Do you know which sites/dates caused the error or was it all of them?

**Comment by Devin-Huyghebaert** [comment]
The first 3 sites had the error, I did not test further than that.  It could be due to merging multiple files, or from having a file starting at 0:00?

**Comment by carleyjmartin** [comment]
Yeah, I was assuming it was gonna be that. Just checking because the SAS data for 2020 isn't on the mirror yet so I can't get it!

**Comment by mts299** [comment]
Thank you @Devin-Huyghebaert! Glad to see your involvement :)

**Comment by carleyjmartin** [comment]
@Devin-Huyghebaert  Let me know how that fix comes along, I didn't test it on SAS as I don't have the data but here's an example from MCM:
```python3
import pydarn
import matplotlib.pyplot as plt
from glob import glob
from collections import deque
import bz2
import datetime

import matplotlib as mpl
mpl.rcParams['figure.figsize'] = 20, 10

#dates
#sas 20200430
#mcm 20161124
#inv 20150929
#hok 20190414
#fhw 20170729

radar_date = ['20161124']
radar_site = ['mcm']

#-----

for x in range(len(radar_site)):

    path='/Users/carley/Documents/data'

    fitacf_data=0

    fitacf_data=deque() 

    date=radar_date[x]
    radar=radar_site[x]


    fitacf_files = glob(f'{path}/{date}*{radar}*fitacf.bz2')
    
    print(path)

    if fitacf_files == []:
        raise Exception('Error: No data for radar {}'.format(radar))

    fitacf_files.sort()

    for fitacf_file in fitacf_files:
        with bz2.open(fitacf_file) as fp:
            fitacf_stream = fp.read()
        fitacf_reader = pydarn.SuperDARNRead(fitacf_stream,True)
        records = fitacf_reader.read_fitacf()
        fitacf_data += records
        print(f'Reading {radar_site[x]} complete...')

    #-----
    for beam_num in range(1):
        fig,ax = plt.subplots(2)
        pydarn.RTP.plot_range_time(fitacf_data, beam_num=beam_num,round_start=False,ax=ax[0])
        pydarn.RTP.plot_range_time(fitacf_data, beam_num=beam_num,round_start=True,ax=ax[1])
        plt.show()
```
Screen Shot 2021-07-07 at 10 06 21 AM

This fix also works for smaller time periods which I was testing on originally.

**Comment by Devin-Huyghebaert** [comment]
Tested, looks to work well.

My opinion is that default should be False, but I understand not wanting to affect previously written code.

From your description above,
"This means that the plot will always have a tick label at the start of the xaxis (if True)."

It appears that the start will always be associated with a tick mark, but not necessarily a label.  Not sure if this is intended behaviour.

Example:
rtp_test_example

**Comment by carleyjmartin** [comment]
Thanks @Devin-Huyghebaert , hmm. It should always start with a tick label if True, that was the original idea way back in the first PR for range time plots. I'll have a look at it again, what data are you plotting in the example?  I wrote this with the intention of using False as my default anyway for pyDARN online - I'm not fussy but there was a small consensus in the earlier PR about wanting the rounding to be there.

**Comment by Devin-Huyghebaert** [comment]
That data was for inuvik.  Here is an example for McMurdo:

rtp_test_example_mcm

`
        pydarn.RTP.plot_range_time(fitacf_data, beam_num=beam_num,round_start=False,ax=ax[0],start_time=datetime.datetime(fitacf_data[0]['time.yr'],fitacf_data[0]['time.mo'],fitacf_data[0]['time.dy'],5,15))
        pydarn.RTP.plot_range_time(fitacf_data, beam_num=beam_num,round_start=True,ax=ax[1],start_time=datetime.datetime(fitacf_data[0]['time.yr'],fitacf_data[0]['time.mo'],fitacf_data[0]['time.dy'],5,15))
        plt.show()
`

**Comment by carleyjmartin** [comment]
Thanks! I'm just running it for McMurdo now, I think I've found the issue, it's with using xticks not just the major ticks.

**Comment by mts299** [comment]
Looking at this PR with changing the `start_time` and `round_start` with the command:

```
pydarn.RTP.plot_range_time(fitacf_data, groundscatter=False, start_time=dt.datetime(2015, 3, 8, 14, 47), round_start=True, zmin=-200, zmax=200, beam_num=0, parameter='v')
```

Seems to work as expected. I was thinking we could do False for range-time but True on summary? 

We can discuss in our monthly meeting as well

**Comment by carleyjmartin** [comment]
Newest commit include an update for the x-axis minor ticks, making sure that they are ON the half hour marks not just at every half hour (only matters if not rounding the start of the plot time so didn't matter before). Some rearranging of comments just to make sure it's in the right place, and placing some of the calculations inside the if round_start: loop so they are not done if you don't want any rounding doing. Also simplified the non-rounding code in the if loop. 

I have tested for range-time, time-series and summary plots for a day of data and for smaller time periods. Would suggest checking out time-series and summary plots if testing again, using `start_time` to emphasize the rounding/not rounding.

The rounding to a label is a little more complicated, so for now `round_start= True` will round to the nearest major tick interval if the tick interval is less than one hour (so will show a label at the start of xaxis), and will round to the previous hour if the tick interval is greater than one hour (may or may not be the interval for the labels). For the majority of cases (i.e. plotting a whole day or plotting 2 hour file of data) you won't notice this as it will round and give you a label at the start anyway.

**Comment by carleyjmartin** [comment]
Last update adds a catch for any zero errors, when it finds a zero it reverts to the set rounding value of 15 minute intervals that we had before these changes - if round_start=True.

**Comment by mts299** [comment]
Works now with short files.

**Pull request merged**
