### PR TITLE
FIX: mlon shifting to MLT for HMB and contours

### PR DESCRIPTION
**Pull request by carleyjmartin**
# Scope 

This PR fixes a bug in the contour plotting in convection maps. A TODO I left out was to add the mlon shifting to MLT out of the functions for plotting HMB and contours. It just so happened that the data we were all testing was generally from the same time of the day where the shift is minimal- but if testing in the early hours or late at night you can see the issue. 
**IF ANYONE HAS SOUTHERN HEMISPHERE MAP DATA PLEASE TEST ME!**

This will probably be required for the release branch as the release branch and develop right now are incorrect in plotting these two.

The vector plotting is all okay though!

**issue:** NA

## Approval

**Number of approvals:** 2 please - to make sure it's scientifically correct

## Test

**matplotlib version**:  3.5.1 
**Note testers: please indicate what version of matplotlib you are using**

```python
import matplotlib.pyplot as plt
import pydarn

map_file = "/Users/carley/Documents/data/maps/20150310.n.map"
map_data = pydarn.SuperDARNRead().read_dmap(map_file)

pydarn.Maps.plot_mapdata(map_data,record=60, 
            parameter=pydarn.MapParams.FITTED_VELOCITY,
            lowlat=60)
plt.show()
```
Will now give:
Screen Shot 2022-04-01 at 2 46 26 PM

This is what it looked like before this fix on current release and develop branch:
Screen Shot 2022-04-01 at 2 36 41 PM

*Reminder, please check your code is:
  - copyrighted (if applicable)
  - Appropriate disclaimer added
  - Modification line filled in (if applicable)*

### CODE REVIEW

**Comment by Shirling-VT** [comment]
MacOS 10.15.7
matplotlib 3.4.2
python 3.8.0

map_file = '/Users/xueling/data/superdarn/2015/map2/north/20150310.north.map2.bz2'
map_data = pydarn.SuperDARNRead().read_dmap(map_file)
data = pydarn.Maps.plot_mapdata(map_data,record=60,
                                parameter=pydarn.MapParams.FITTED_VELOCITY,
                                lowlat=60)

plt.show()

image
@carleyjmartin, pretty close to what you got, although I have IMF dial and other meta data in the figure, maybe because other relevant pr was merged? The vectors and contours are slightly different, probably due to the different data files we used (I'm using map2 file). Another minor thing I noticed is that the 06 hour mlt annotation on the right is blocked by the velocity color bar, can we move the color bar slightly right?

map_file = '/Users/xueling/data/superdarn/2019/map2/south/20190421.south.map2.bz2'
map_data = pydarn.SuperDARNRead().read_dmap(map_file)
data = pydarn.Maps.plot_mapdata(map_data,start_time=dt.datetime(2019,4,21,22,58),
                                parameter=pydarn.MapParams.FITTED_VELOCITY,
                                lowlat=60)
plt.show()
image

The contours are not shown in the southern hemisphere plot. And the vectors look differently to those generated from the VT website using the same data:
image

There may be an issue with plotting map data from the southern hemisphere.

**Comment by carleyjmartin** [comment]
Hey @Shirling-VT 
I have had a play with some southern hemisphere data and I think I've worked it out to work with them, I only have a limited selection of data to play with and it's got a few caveats as it was made specially with the inertial flag.
Anyway, this is what I get when running: 
```python
import matplotlib.pyplot as plt
import pydarn

#map_file = "/Users/carley/Documents/data/maps/20150310.n.map"
map_file = "/Users/carley/Documents/data/maps/20170113.s.map"
map_data = pydarn.SuperDARNRead().read_dmap(map_file)
pydarn.Maps.plot_mapdata(map_data,record=65, 
            parameter=pydarn.MapParams.FITTED_VELOCITY,
            lowlat=60)
plt.show()
```

Screen Shot 2022-04-05 at 10 55 49 AM


There's not many vectors to see, but they don't seem to be following the contours, I think it's a simple `if southern:` sort of deal figuring out the sock directions. I'll have a look and see if its something I can just tag onto this PR but it might be that it needs its own. 
I don't have any map2 or 2019 data to test with, can you send me the map file at carley.martin@usask.ca if possible? Thank you!

**Comment by KhanalKrishna** [comment]
**MacOS Catalina 10.15.7
matplotlib 3.4.3
python 3.9.7**


import matplotlib.pyplot as plt
import pydarn

map_file = "20190111.north.map2"
map_data = pydarn.SuperDARNRead().read_dmap(map_file)

pydarn.Maps.plot_mapdata(map_data,record=60, 
            parameter=pydarn.MapParams.FITTED_VELOCITY,
            lowlat=60)
plt.savefig("testmap.png")
plt.show()


image

**Comment by billetd** [comment]
Sorted out the southern hemisphere vectors by treating them as if they were in the north and then just flipping the sign of a bunch of values (specifically, `azm_v` and `vecx`/`vecy`). This will keep northern hemisphere data working correctly. 

Southern hemisphere data:
```python
import datetime as dt
import pydarn
import matplotlib.pyplot as plt

map_file = "/Users/danielbillett/pydarn/pydarntesting/20190421.s.map2"
map_data = pydarn.SuperDARNRead().read_dmap(map_file)
pydarn.Maps.plot_mapdata(map_data,start_time=dt.datetime(2019,4,21,23,42), 
            parameter=pydarn.MapParams.FITTED_VELOCITY,
            lowlat=60)
plt.show()
```
Result: 
south

Northern hemisphere data:
```python
import datetime as dt
import pydarn
import matplotlib.pyplot as plt

map_file = "/Users/danielbillett/pydarn/pydarntesting/20150310.north.map2"
map_data = pydarn.SuperDARNRead().read_dmap(map_file)
pydarn.Maps.plot_mapdata(map_data,start_time=dt.datetime(2015,3,10,11,8), 
            parameter=pydarn.MapParams.FITTED_VELOCITY,
            lowlat=60)
plt.show()
```
Result:
north

**Review by billetd — APPROVED** [review]

**Pull request merged**
