### PR TITLE
EHN: Single Beam Options

### PR DESCRIPTION
**Pull request by carleyjmartin**
# Scope 

This PR contains an addition to the `fan.py` module that allows for the option `beam` to be passed to the fov and fan plotting functions. This allows the user to plot more specific data, or make diagrams with beams in fov.  The examples below use a file that is using camping beam,  which is a good use case/option to plot single beams. Default for `beam` is `None`. Docs updated. 

**issue:** #294 

## Approval

**Number of approvals:** 2 test and code review

## Test

**matplotlib version**: 3.6.3
**Note testers: please indicate what version of matplotlib you are using**

```python
import matplotlib.pyplot as plt
import pydarn
import datetime as dt

file = "/Users/carley/Documents/data/20150308.1400.03.cly.fitacf"
SDarn_read = pydarn.SuperDARNRead(file)
fitacf_data = SDarn_read.read_fitacf()

# FOV plot highlighting geographic and magnetic
_, _ , ax, ccrs = pydarn.Fan.plot_fov(fitacf_data[0]['stid'], dt.datetime(2015,3,8,14,10), beam=10, grid=True, fov_color='red',coords=pydarn.Coords.GEOGRAPHIC ,projs=pydarn.Projs.GEO, coastline=True, lowlat=50)
_, _, ax, ccrs = pydarn.Fan.plot_fov(fitacf_data[0]['stid'], dt.datetime(2015,3,8,14,10), ax=ax, ccrs=ccrs, beam=4, grid=True, fov_color='blue',ranges=[30,60], coords=pydarn.Coords.GEOGRAPHIC ,projs=pydarn.Projs.GEO)
_, _, ax, ccrs = pydarn.Fan.plot_fov(fitacf_data[0]['stid'], dt.datetime(2015,3,8,14,10), ax=ax, ccrs=ccrs, coords=pydarn.Coords.GEOGRAPHIC ,projs=pydarn.Projs.GEO)
plt.show()

_, _, ax, _ = pydarn.Fan.plot_fov(fitacf_data[0]['stid'], dt.datetime(2015,3,8,14,10), beam=10, grid=True, fov_color='red', coastline=True, lowlat=50)
_, _, ax, _ = pydarn.Fan.plot_fov(fitacf_data[0]['stid'], dt.datetime(2015,3,8,14,10), ax=ax, beam=4, grid=True, fov_color='blue',ranges=[30,60])
_, _, ax, _ = pydarn.Fan.plot_fov(fitacf_data[0]['stid'], dt.datetime(2015,3,8,14,10), ax=ax)
plt.show()

# Fan plot with specific data in geo and mag
_, _, ax, ccrs = pydarn.Fan.plot_fov(fitacf_data[0]['stid'], dt.datetime(2015,3,8,14,10), coastline=True, lowlat=50, coords=pydarn.Coords.GEOGRAPHIC ,projs=pydarn.Projs.GEO)
pydarn.Fan.plot_fan(fitacf_data, scan_index=dt.datetime(2015,3,8,14,10), beam=10, boundary=True,radar_label=True, groundscatter=True, ax=ax, colorbar=False, coords=pydarn.Coords.GEOGRAPHIC ,projs=pydarn.Projs.GEO)
pydarn.Fan.plot_fan(fitacf_data, scan_index=dt.datetime(2015,3,8,14,10), beam=4, ranges=[30,60], boundary=True, radar_label=True, groundscatter=True, ax=ax, coords=pydarn.Coords.GEOGRAPHIC ,projs=pydarn.Projs.GEO)
plt.show()

_, _, ax, _ = pydarn.Fan.plot_fov(fitacf_data[0]['stid'], dt.datetime(2015,3,8,14,10), coastline=True, lowlat=50)
pydarn.Fan.plot_fan(fitacf_data, scan_index=dt.datetime(2015,3,8,14,10), beam=10, boundary=True,radar_label=True, groundscatter=True, ax=ax, colorbar=False)
pydarn.Fan.plot_fan(fitacf_data, scan_index=dt.datetime(2015,3,8,14,10), beam=4, ranges=[30,60], boundary=True, radar_label=True, groundscatter=True, ax=ax)
plt.show()
```
The above code, produces the following plots:

Screenshot 2023-02-06 at 12 48 38 PM
Screenshot 2023-02-06 at 12 48 51 PM
Screenshot 2023-02-06 at 12 49 06 PM
Screenshot 2023-02-06 at 12 49 23 PM

### CODE REVIEW

**Comment by KhanalKrishna** [comment]
Hi, 
I am receiving a value error:

Matplotlib version: 3.6.3

import matplotlib.pyplot as plt
import pydarn
import datetime as dt

file = "20150308.1400.03.cly.fitacf"
SDarn_read = pydarn.SuperDARNRead(file)
fitacf_data = SDarn_read.read_fitacf()

# FOV plot highlighting geographic and magnetic
_, _ , ax, ccrs = pydarn.Fan.plot_fov(fitacf_data[0]['stid'], dt.datetime(2015,3,8,14,10), beam=10, grid=True, fov_color='red',coords=pydarn.Coords.GEOGRAPHIC ,projs=pydarn.Projs.GEO, coastline=True, lowlat=50)
_, _, ax, ccrs = pydarn.Fan.plot_fov(fitacf_data[0]['stid'], dt.datetime(2015,3,8,14,10), ax=ax, ccrs=ccrs, beam=4, grid=True, fov_color='blue',ranges=[30,60], coords=pydarn.Coords.GEOGRAPHIC ,projs=pydarn.Projs.GEO)
_, _, ax, ccrs = pydarn.Fan.plot_fov(fitacf_data[0]['stid'], dt.datetime(2015,3,8,14,10), ax=ax, ccrs=ccrs, coords=pydarn.Coords.GEOGRAPHIC ,projs=pydarn.Projs.GEO)
plt.show()

_, _, ax, _ = pydarn.Fan.plot_fov(fitacf_data[0]['stid'], dt.datetime(2015,3,8,14,10), beam=10, grid=True, fov_color='red', coastline=True, lowlat=50)
_, _, ax, _ = pydarn.Fan.plot_fov(fitacf_data[0]['stid'], dt.datetime(2015,3,8,14,10), ax=ax, beam=4, grid=True, fov_color='blue',ranges=[30,60])
_, _, ax, _ = pydarn.Fan.plot_fov(fitacf_data[0]['stid'], dt.datetime(2015,3,8,14,10), ax=ax)
plt.show()


# Fan plot with specific data in geo and mag
_, _, ax, ccrs = pydarn.Fan.plot_fov(fitacf_data[0]['stid'], dt.datetime(2015,3,8,14,10), coastline=True, lowlat=50, coords=pydarn.Coords.GEOGRAPHIC ,projs=pydarn.Projs.GEO)
pydarn.Fan.plot_fan(fitacf_data, scan_index=dt.datetime(2015,3,8,14,10), beam=10, boundary=True,radar_label=True, groundscatter=True, ax=ax, colorbar=False, coords=pydarn.Coords.GEOGRAPHIC ,projs=pydarn.Projs.GEO)
pydarn.Fan.plot_fan(fitacf_data, scan_index=dt.datetime(2015,3,8,14,10), beam=4, ranges=[30,60], boundary=True, radar_label=True, groundscatter=True, ax=ax, coords=pydarn.Coords.GEOGRAPHIC ,projs=pydarn.Projs.GEO)
plt.show()

_, _, ax, _ = pydarn.Fan.plot_fov(fitacf_data[0]['stid'], dt.datetime(2015,3,8,14,10), coastline=True, lowlat=50)
pydarn.Fan.plot_fan(fitacf_data, scan_index=dt.datetime(2015,3,8,14,10), beam=10, boundary=True,radar_label=True, groundscatter=True, ax=ax, colorbar=False)
pydarn.Fan.plot_fan(fitacf_data, scan_index=dt.datetime(2015,3,8,14,10), beam=4, ranges=[30,60], boundary=True, radar_label=True, groundscatter=True, ax=ax)
plt.show()



Message:
IMPORTANT: Please make sure to cite pyDARN in publications that use plots created by pyDARN using DOI: https://zenodo.org/record/3727269. Citing information for SuperDARN data is found at https://pydarn.readthedocs.io/en/master/user/citing/
Traceback (most recent call last):
  File "/Users/krishna/Desktop/pydarn_testing/pr298.py", line 10, in <module>
    _, _ , ax, ccrs = pydarn.Fan.plot_fov(fitacf_data[0]['stid'], dt.datetime(2015,3,8,14,10), beam=10, grid=True, fov_color='red',coords=pydarn.Coords.GEOGRAPHIC ,projs=pydarn.Projs.GEO, coastline=True, lowlat=50)
  File "/Users/krishna/.local/lib/python3.9/site-packages/pydarn/plotting/fan.py", line 472, in plot_fov
    ax, ccrs = projs(date=date, **kwargs)
  File "/Users/krishna/.local/lib/python3.9/site-packages/pydarn/plotting/projections.py", line 217, in __call__
    return self.value[0](*args, **kwargs)
  File "/Users/krishna/.local/lib/python3.9/site-packages/pydarn/plotting/projections.py", line 191, in axis_geological
    ax = plt.subplot(111, projection=proj, aspect='auto')
  File "/Users/krishna/opt/anaconda3/lib/python3.9/site-packages/matplotlib/pyplot.py", line 1287, in subplot
    ax = fig.add_subplot(*args, **kwargs)
  File "/Users/krishna/opt/anaconda3/lib/python3.9/site-packages/matplotlib/figure.py", line 746, in add_subplot
    ax = subplot_class_factory(projection_class)(self, *args, **pkw)
  File "/Users/krishna/opt/anaconda3/lib/python3.9/site-packages/matplotlib/axes/_subplots.py", line 34, in __init__
    self._axes_class.__init__(self, fig, [0, 0, 1, 1], **kwargs)
  File "/Users/krishna/opt/anaconda3/lib/python3.9/site-packages/cartopy/mpl/geoaxes.py", line 413, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/krishna/opt/anaconda3/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 653, in __init__
    self.clear()
  File "/Users/krishna/opt/anaconda3/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 1339, in clear
    self.cla()
  File "/Users/krishna/opt/anaconda3/lib/python3.9/site-packages/cartopy/mpl/geoaxes.py", line 607, in cla
    self._boundary()
  File "/Users/krishna/opt/anaconda3/lib/python3.9/site-packages/cartopy/mpl/geoaxes.py", line 1602, in _boundary
    trans_path = proj_to_data.transform_path(path)
  File "/Users/krishna/opt/anaconda3/lib/python3.9/site-packages/matplotlib/transforms.py", line 1595, in transform_path
    return self.transform_path_affine(self.transform_path_non_affine(path))
  File "/Users/krishna/opt/anaconda3/lib/python3.9/site-packages/cartopy/mpl/geoaxes.py", line 170, in transform_path_non_affine
    new_vertices = self.target_projection.quick_vertices_transform(
  File "/Users/krishna/opt/anaconda3/lib/python3.9/site-packages/cartopy/crs.py", line 1247, in quick_vertices_transform
    if (x.min() >= x_limits[0] and x.max() <= x_limits[1] and
  File "/Users/krishna/opt/anaconda3/lib/python3.9/site-packages/numpy/core/_methods.py", line 44, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial, where)
ValueError: zero-size array to reduction operation minimum which has no identity

**Comment by carleyjmartin** [comment]
Hi @KhanalKrishna I can't recreate the error, does the code still work if you try to plot without the beam options? Also whats your numpy version?

**Comment by KhanalKrishna** [comment]
Hi @carleyjmartin,
Sorry for the late response. 
Yes, I think it is due to cartopy. However, I am now getting trouble  re-installing shapely and cartopy. I will get back to it later and try with updated packages.

**Comment by Shirling-VT** [comment]
Tested in 
MacOS Monterey 12.5.1 
matplotlib 3.4.2
python 3.8.0
It's working fine for me using the codes Carley provided.
image
image
image
image

**Comment by KhanalKrishna** [comment]
matplotlib version: 3.5.3

Hi @carleyjmartin, for some data files, the beams in last two plots extend beyond the radar FOV. I changed only filename and date_time. 

import matplotlib.pyplot as plt
import pydarn
import datetime as dt

#file= "20150308.1400.03.cly.fitacf"
#file = "20180225.1801.00.inv.fitacf"
file= "20130202.2001.00.inv.fitacf"
SDarn_read = pydarn.SuperDARNRead(file)
fitacf_data = SDarn_read.read_fitacf()

#date_time= dt.datetime(2015,3,8,14,10)
#date_time= dt.datetime(2018,2,25,18,10)
date_time= dt.datetime(2013, 2, 2, 20, 30)

# FOV plot highlighting geographic and magnetic
_, _ , ax, ccrs = pydarn.Fan.plot_fov(fitacf_data[0]['stid'], date_time, beam=10, grid=True, fov_color='red',coords=pydarn.Coords.GEOGRAPHIC ,projs=pydarn.Projs.GEO, coastline=True, lowlat=50)
_, _, ax, ccrs = pydarn.Fan.plot_fov(fitacf_data[0]['stid'], date_time, ax=ax, ccrs=ccrs, beam=4, grid=True, fov_color='blue',ranges=[30,60], coords=pydarn.Coords.GEOGRAPHIC ,projs=pydarn.Projs.GEO)
_, _, ax, ccrs = pydarn.Fan.plot_fov(fitacf_data[0]['stid'], date_time, ax=ax, ccrs=ccrs, coords=pydarn.Coords.GEOGRAPHIC ,projs=pydarn.Projs.GEO)
plt.show()

_, _, ax, _ = pydarn.Fan.plot_fov(fitacf_data[0]['stid'], date_time, beam=10, grid=True, fov_color='red', coastline=True, lowlat=50)
_, _, ax, _ = pydarn.Fan.plot_fov(fitacf_data[0]['stid'], date_time, ax=ax, beam=4, grid=True, fov_color='blue',ranges=[30,60])
_, _, ax, _ = pydarn.Fan.plot_fov(fitacf_data[0]['stid'], date_time, ax=ax)
plt.show()

# Fan plot with specific data in geo and mag
_, _, ax, ccrs = pydarn.Fan.plot_fov(fitacf_data[0]['stid'], date_time, coastline=True, lowlat=50, coords=pydarn.Coords.GEOGRAPHIC ,projs=pydarn.Projs.GEO)
pydarn.Fan.plot_fan(fitacf_data, scan_index=date_time, beam=10, boundary=True,radar_label=True, groundscatter=True, ax=ax, colorbar=False, coords=pydarn.Coords.GEOGRAPHIC ,projs=pydarn.Projs.GEO)
pydarn.Fan.plot_fan(fitacf_data, scan_index=date_time, beam=4, ranges=[30,60], boundary=True, radar_label=True, groundscatter=True, ax=ax, coords=pydarn.Coords.GEOGRAPHIC ,projs=pydarn.Projs.GEO)
plt.show()

_, _, ax, _ = pydarn.Fan.plot_fov(fitacf_data[0]['stid'], date_time, coastline=True, lowlat=50)
pydarn.Fan.plot_fan(fitacf_data, scan_index=date_time, beam=10, boundary=True,radar_label=True, groundscatter=True, ax=ax, colorbar=False)
pydarn.Fan.plot_fan(fitacf_data, scan_index=date_time, beam=4, ranges=[30,60], boundary=True, radar_label=True, groundscatter=True, ax=ax)
plt.show()

image

image

image

image

**Comment by carleyjmartin** [comment]
Thanks for testing @KhanalKrishna ! I'll look into it, although I think it might be an issue with the FOV using 'defaults' we put in and then the fan plot using the real data from a file! Might be adjustable using `ranges=[0,110]` or something similar in the FOV plot.

**Comment by hiyadutuje** [comment]
Figure_7
Figure_8
Figure_9
Figure_10
These are the plots I am getting.

**Pull request merged**
