### PR TITLE
EHN: Grid plots in Geographic Coordinates

### LINKED ISSUE #250: Refactor Grid plotting code
# New Feature

## Scope

To refactor the grid file plotting code like I did with the Fan code to reduce an tightly coupled stuff. It should not change the functionality of the code. 

### pyDARN Checklist 

-  [x] Does this fit within pyDARN's scope? 
-  [x] Is this a minor change i.e., new small utility function?

### PR DESCRIPTION
**Pull request by carleyjmartin**
# Scope 

This PR refactors the grid.py plotting code to include the option to plot in geographic coordinates. 
I personally wasn't going to do geographic for convection maps as no one really has asked for it and I don't need it, but this might be worth discussing more at the next meeting.
This branch is branched from current develop so some bugs are fixed in other PRs (like the colorbar extending below 0 when it shouldn't)

You may also note from the branch name that I was originally trying to fix a bug from #238 but then ended up with this fix instead. I'll keep going with the matplotlib axes, but it might just be an issue we can't resolve. It is possible to overplot fan and fov plots in any coords/projs, you just need to correct ax/ccrs read in which I will write up to docs. 

**issue:** to close #250 and mentioned in #278

## Approval

**Number of approvals:** 2 - Please also test with southern grid files!

## Test

**matplotlib version**: 3.5.3
**Note testers: please indicate what version of matplotlib you are using**

```python
import matplotlib.pyplot as plt 
import pydarn

grid_file = "/Users/carley/Documents/data/grids/20011220.8000.grid"
grid_data = pydarn.SuperDARNRead(grid_file).read_grid()

plt.figure(figsize=(9,7))
fanplot = pydarn.Grid.plot_grid(grid_data, parameter = 'vel', 
                radar_label=True, radar_location=True, fov_color='grey', 
                lowlat=50, coastline=True, coords=pydarn.Coords.GEOGRAPHIC,
                projs=pydarn.Projs.GEO, colorbar_label='Velocity km/s')
plt.show()

plt.figure(figsize=(9,7))
fanplot = pydarn.Grid.plot_grid(grid_data, parameter = 'vel', 
                radar_label=True, radar_location=True, fov_color='grey', 
                lowlat=50, coastline=True, colorbar_label='Velocity km/s')
plt.show()
```
Screen Shot 2022-08-29 at 12 11 55 PM
Screen Shot 2022-08-29 at 12 12 08 PM

*Reminder, please check your code is:
  - copyrighted (if applicable)
  - Appropriate disclaimer added
  - Modification line filled in (if applicable)*

### CODE REVIEW

**Comment by Shirling-VT** [comment]
The northern hemisphere works fine for me, but when I tried to plot the southern hemisphere, it does not work. It will show the map still in the northern hemisphere with no data overlaid. We should add the hemisphere information when creating the projection and ax, right?

**Comment by carleyjmartin** [comment]
Hey, yes, I don't have any southern grid files to test with and I can't make any right now (long story), if you have some southern grid files and can send them to me I should be able to add in the logic for southern hemisphere.

**Comment by Shirling-VT** [comment]
@carleyjmartin I think the hemisphere information is stored in the grid file name, but not sure if this is always the case. I think your way of checking the actual latitude data would work pretty well. I'll test it again later today for the southern hemisphere.

**Comment by carleyjmartin** [comment]
Doing it this way will also work for single radar grid files, which is a bonus, and people can change filenames so avoiding using the file name is probably best practice here, I guess?

**Comment by Shirling-VT** [comment]
The southern hemisphere is now working for me, here are my codes for testing:
#MacOS Monterey 12.5.1
#matplotlib 3.4.2
#python 3.8.0

import matplotlib.pyplot as plt
import pydarn

grid_south = "/Users/xueling/data/superdarn/2015/grid2/south/20150317.south.grid2"
grid_data_south = pydarn.SuperDARNRead(grid_south).read_grid()

plt.figure(figsize=(9,7))
fanplot = pydarn.Grid.plot_grid(grid_data_south, parameter = 'vel', 
                radar_label=True, radar_location=True, fov_color='grey', 
                lowlat=40, coastline=True, coords=pydarn.Coords.GEOGRAPHIC,
                projs=pydarn.Projs.GEO, colorbar_label='Velocity km/s')
plt.show()

image

plt.figure(figsize=(9,7))
fanplot = pydarn.Grid.plot_grid(grid_data_south,parameter = 'vel', 
                radar_label=True, radar_location=True, fov_color='grey', 
                lowlat=40, coastline=True, colorbar_label='Velocity km/s')
plt.show()

image

I also compared the MLT coord plot with those from the VT website, they look good to me.

**Comment by carleyjmartin** [comment]
Awesome!

**Pull request merged**
