### PR TITLE
EHN: Geo/AACGM Lat/Lon and MLT as y-axis options for RTP

### PR DESCRIPTION
**Pull request by carleyjmartin**
# Scope 

This PR adds the option to plot the y-axis in range time plots and summary plots as geographic latitude or longitude, AACGM latitude or longitude or AACGM derived MLT.

I'm reusing the coords enum, but I'm not using the coords methods to convert. The user will choose a range estimate value from slant range, half slant range, GSMR or range gates. If the first three are chosen, the user can opt to convert the axes values into geographic latitude or longitude, magnetic latitude or longitude or MLT using the coords keyword. Latitude and longitude for both is controlled by a new keyword called 'lat_or_lon', where the user can choose 'lat' or 'lon' to input. This defaults to 'lat' with no user input. These options work for both summary and range time plots. 

Please note that this method does not 'plot' in latitude, longitude or MLT, it converts the y-axis values into a coordinate or MLT. The coordinates are not linear and sometimes reverse, as such actually plotting in those does not make sense as the plot will be a mess. The plot will plot in the range_estimate chosen, of which the values on the axis are converted. All lats lons and MLTs are rounded to nearest 1 dp.

I attempted to add a secondary axis, but it's far more work that I can do right now to get it working with summary plots and make it a nice user experience - so it's probably best as a future PR on it's own for testing purposes. 

**issue:** #272 

## Approval

**Number of approvals:** 2 please, there is ALOT of testing required for this with various different options. 

## Test

**matplotlib version**: 3.5.3
**Note testers: please indicate what version of matplotlib you are using**

This is only some of the options:
```python
import matplotlib.pyplot as plt 
import pydarn

file = "/Users/carley/Documents/data/20160120.1602.00.cly.fitacf"
SDarn_read = pydarn.SuperDARNRead(file)
fitacf_data = SDarn_read.read_fitacf()

# --------------Basic RANGE_GATES to compare --------------
a = pydarn.RTP.plot_range_time(fitacf_data, beam_num=10,
                               zmin=-400, zmax=400, groundscatter=True,
                               range_estimation=pydarn.RangeEstimation.RANGE_GATE)
plt.show()
a = pydarn.RTP.plot_summary(fitacf_data, beam_num=10,
                            range_estimation=pydarn.RangeEstimation.RANGE_GATE)
plt.show()

# --------------AACGM Longitude from Slant Ranges --------------
a = pydarn.RTP.plot_range_time(fitacf_data, beam_num=10,
                               zmin=-400, zmax=400, groundscatter=True,
                               range_estimation=pydarn.RangeEstimation.SLANT_RANGE,
                               coords=pydarn.Coords.AACGM,
                               lat_or_lon = 'lon')
plt.show()
a = pydarn.RTP.plot_summary(fitacf_data, beam_num=10,
                            range_estimation=pydarn.RangeEstimation.SLANT_RANGE,
                            coords=pydarn.Coords.AACGM, lat_or_lon="lon")
plt.show()

# --------------Geographic Latitude from GSMR ranges --------------
a = pydarn.RTP.plot_range_time(fitacf_data, beam_num=10,
                               zmin=-400, zmax=400, groundscatter=True,
                               range_estimation=pydarn.RangeEstimation.GSMR,
                               coords=pydarn.Coords.GEOGRAPHIC, lat_or_lon='lat')
plt.show()
a = pydarn.RTP.plot_summary(fitacf_data, beam_num=10,
                            range_estimation=pydarn.RangeEstimation.GSMR,
                            coords=pydarn.Coords.GEOGRAPHIC, lat_or_lon='lat')
plt.show()


# All options include:
# range_estimate = pydarn.RangeEstimation.RANGE_GATE
#                  pydarn.RangeEstimation.SLANT_RANGE
#                  pydarn.RangeEstimation.GSMR
#                  pydarn.RangeEstimation.HALF_SLANT

# If above chosen with no coords, coords = None and the above will be plotted.
# If coords is chosen then the above will be used to plot and then converted to
# lat or lon given below options.

# coords = pydarn.Coords.GEOGRAPHIC
#          pydarn.Coords.AACGM
#          pydarn.Coords.AACGM_MLT

# If GEOGRAPHIC or AACGM Chosen (defaults to lat)
# lat_or_lon = 'lat'
#              'lon'

# If AACGM_MLT chosen the code will plot MLT
```

And produces the following summary plots (not shown are the range-time plots produced too):
Screen Shot 2022-08-18 at 3 24 49 PM
Screen Shot 2022-08-18 at 3 25 18 PM
Screen Shot 2022-08-18 at 3 26 58 PM
It's normal for the bottom bits to fall off with GSMR- that's how it works.

### CODE REVIEW

**Comment by KhanalKrishna** [comment]
# AACGM Latitude from Slant Ranges 
a = pydarn.RTP.plot_range_time(fitacf_data, beam_num=10,
                               zmin=-400, zmax=400, groundscatter=True,
                               range_estimation=pydarn.RangeEstimation.SLANT_RANGE,
                               coords=pydarn.Coords.AACGM, lat_or_lon='lat')
plt.savefig("AACGM Latitude from Slant Ranges.png", dpi= 1000)
plt.show()

AACGM Latitude from Slant Ranges



# AACGM Latitude from Range Gates 
a = pydarn.RTP.plot_range_time(fitacf_data, beam_num=10,
                               zmin=-400, zmax=400, groundscatter=True,
                               range_estimation=pydarn.RangeEstimation.RANGE_GATE,
                               coords=pydarn.Coords.AACGM, lat_or_lon='lat')
plt.savefig("AACGM Latitude from Range Gates", dpi= 1000)
plt.show()

AACGM Latitude from Range Gates



# AACGM Latitude from GSMR
a = pydarn.RTP.plot_range_time(fitacf_data, beam_num=10,
                               zmin=-400, zmax=400, groundscatter=True,
                               range_estimation=pydarn.RangeEstimation.GSMR,
                               coords=pydarn.Coords.AACGM, lat_or_lon='lat')
plt.savefig("AACGM Latitude from GSMR", dpi= 1000)
plt.show()


AACGM Latitude from GSMR



# AACGM Latitude from HALF_SLANT
a = pydarn.RTP.plot_range_time(fitacf_data, beam_num=10,
                               zmin=-400, zmax=400, groundscatter=True,
                               range_estimation=pydarn.RangeEstimation.HALF_SLANT,
                               coords=pydarn.Coords.AACGM)
plt.savefig("AACGM Latitude from HALF_SLANT.png", dpi= 1000, lat_or_lon='lat')
plt.show()

AACGM Latitude from HALF_SLANT




# AACGM Longitude from Slant Ranges 
a = pydarn.RTP.plot_range_time(fitacf_data, beam_num=10,
                               zmin=-400, zmax=400, groundscatter=True,
                               range_estimation=pydarn.RangeEstimation.SLANT_RANGE,
                               coords=pydarn.Coords.AACGM, lat_or_lon='lon')
plt.savefig("AACGM Longitude from Slant Ranges.png", dpi= 1000)
plt.show()
AACGM Longitude from Slant Ranges



# AACGM Longitude from Range Gates 
a = pydarn.RTP.plot_range_time(fitacf_data, beam_num=10,
                               zmin=-400, zmax=400, groundscatter=True,
                               range_estimation=pydarn.RangeEstimation.RANGE_GATE,
                               coords=pydarn.Coords.AACGM, lat_or_lon='lon')
plt.savefig("AACGM Latitude from Range Gates.png", dpi= 1000)
plt.show()
AACGM Longitude from Range Gates


# AACGM Longitude from GSMR
a = pydarn.RTP.plot_range_time(fitacf_data, beam_num=10,
                               zmin=-400, zmax=400, groundscatter=True,
                               range_estimation=pydarn.RangeEstimation.GSMR,
                               coords=pydarn.Coords.AACGM, lat_or_lon='lon')
plt.savefig("AACGM Longitude from GSMR.png", dpi= 1000)
plt.show()

AACGM Longitude from GSMR


# AACGM Longitude from HALF_SLANT
a = pydarn.RTP.plot_range_time(fitacf_data, beam_num=10,
                               zmin=-400, zmax=400, groundscatter=True,
                               range_estimation=pydarn.RangeEstimation.HALF_SLANT,
                               coords=pydarn.Coords.AACGM)
plt.savefig("AACGM Longitude from HALF_SLANT.png", dpi= 1000)
plt.show()
AACGM Longitude from HALF_SLANT


# GEOGRAPHIC Latitude from Slant Ranges 
a = pydarn.RTP.plot_range_time(fitacf_data, beam_num=10,
                               zmin=-400, zmax=400, groundscatter=True,
                               range_estimation=pydarn.RangeEstimation.SLANT_RANGE,
                               coords=pydarn.Coords.GEOGRAPHIC, lat_or_lon='lat')
plt.savefig("GEOGRAPHIC Latitude from Slant Ranges.png", dpi= 1000)
plt.show()

GEOGRAPHIC Latitude from Slant Ranges

# GEOGRAPHIC Latitude from Range Gates 
a = pydarn.RTP.plot_range_time(fitacf_data, beam_num=10,
                               zmin=-400, zmax=400, groundscatter=True,
                               range_estimation=pydarn.RangeEstimation.RANGE_GATE,
                               coords=pydarn.Coords.GEOGRAPHIC, lat_or_lon='lat')
plt.savefig("GEOGRAPHIC Latitude from Range Gates", dpi= 1000)
plt.show()
GEOGRAPHIC Latitude from Range Gates



# GEOGRAPHIC Latitude from GSMR
a = pydarn.RTP.plot_range_time(fitacf_data, beam_num=10,
                               zmin=-400, zmax=400, groundscatter=True,
                               range_estimation=pydarn.RangeEstimation.GSMR,
                               coords=pydarn.Coords.GEOGRAPHIC, lat_or_lon='lat')
plt.savefig("GEOGRAPHIC Latitude from GSMR", dpi= 1000)
plt.show()
GEOGRAPHIC Latitude from GSMR




# GEOGRAPHIC Latitude from HALF_SLANT
a = pydarn.RTP.plot_range_time(fitacf_data, beam_num=10,
                               zmin=-400, zmax=400, groundscatter=True,
                               range_estimation=pydarn.RangeEstimation.HALF_SLANT,
                               coords=pydarn.Coords.GEOGRAPHIC)
plt.savefig("GEOGRAPHIC Latitude from HALF_SLANT.png", dpi= 1000, lat_or_lon='lat')
plt.show()

GEOGRAPHIC Latitude from HALF_SLANT

# GEOGRAPHIC Longitude from Slant Ranges 
a = pydarn.RTP.plot_range_time(fitacf_data, beam_num=10,
                               zmin=-400, zmax=400, groundscatter=True,
                               range_estimation=pydarn.RangeEstimation.SLANT_RANGE,
                               coords=pydarn.Coords.GEOGRAPHIC, lat_or_lon='lon')
plt.savefig("GEOGRAPHIC Lon
GEOGRAPHIC Longitude from Slant Ranges
gitude from Slant Ranges.png", dpi= 1000)
plt.show()

# GEOGRAPHIC Longitude from Range Gates 
a = pydarn.RTP.plot_range_time(fitacf_data, beam_num=10,
                               zmin=-400, zmax=400, groundscatter=True,
                               range_estimation=pydarn.RangeEstimation.RANGE_GATE,
                               coords=pydarn.Coords.GEOGRAPHIC, lat_or_lon='lon')
plt.savefig("GEOGRAPHIC longitude  from Range Gates.png", dpi= 1000)
plt.show()
GEOGRAPHIC longitude  from Range Gates


# GEOGRAPHIC Longitude from GSMR
a = pydarn.RTP.plot_range_time(fitacf_data, beam_num=10,
                               zmin=-400, zmax=400, groundscatter=True,
                               range_estimation=pydarn.RangeEstimation.GSMR,
                               coords=pydarn.Coords.GEOGRAPHIC, lat_or_lon='lon')
plt.savefig("GEOGRAPHIC Longitude from GSMR.png", dpi= 1000)
plt.show()
GEOGRAPHIC Longitude from GSMR




# GEOGRAPHIC Longitude from HALF_SLANT
a = pydarn.RTP.plot_range_time(fitacf_data, beam_num=10,
                               zmin=-400, zmax=400, groundscatter=True,
                               range_estimation=pydarn.RangeEstimation.HALF_SLANT,
                               coords=pydarn.Coords.GEOGRAPHIC,lat_or_lon='lon')
plt.savefig("GEOGRAPHIC Longitude from HALF_SLANT.png", dpi= 1000)
plt.show()

GEOGRAPHIC Longitude from HALF_SLANT


# AACGM_MLT Latitude from Slant Ranges 
a = pydarn.RTP.plot_range_time(fitacf_data, beam_num=10,
                               zmin=-400, zmax=400, groundscatter=True,
                               range_estimation=pydarn.RangeEstimation.SLANT_RANGE,
                               coords=pydarn.Coords.AACGM_MLT, lat_or_lon='lat')
plt.savefig("AACGM_MLT Latitude from Slant Ranges.png", dpi= 1000)
plt.show()
AACGM_MLT Latitude from Slant Ranges

# AACGM_MLT Latitude from Range Gates 
a = pydarn.RTP.plot_range_time(fitacf_data, beam_num=10,
                               zmin=-400, zmax=400, groundscatter=True,
                               range_estimation=pydarn.RangeEstimation.RANGE_GATE,
                               coords=pydarn.Coords.AACGM_MLT, lat_or_lon='lat')
plt.savefig("AACGM_MLT Latitude from Range Gates", dpi= 1000)
plt.show()

AACGM_MLT Latitude from Range Gates

# AACGM_MLT Latitude from GSMR
a = pydarn.RTP.plot_range_time(fitacf_data, beam_num=10,
                               zmin=-400, zmax=400, groundscatter=True,
                               range_estimation=pydarn.RangeEstimation.GSMR,
                               coords=pydarn.Coords.AACGM_MLT, lat_or_lon='lat')
plt.savefig("AACGM_MLT Latitude from GSMR", dpi= 1000)
plt.show()

AACGM_MLT Latitude from GSMR


# AACGM_MLT Latitude from HALF_SLANT
a = pydarn.RTP.plot_range_time(fitacf_data, beam_num=10,
                               zmin=-400, zmax=400, groundscatter=True,
                               range_estimation=pydarn.RangeEstimation.HALF_SLANT,
                               coords=pydarn.Coords.AACGM_MLT)
plt.savefig("AACGM_MLT Latitude from HALF_SLANT.png", dpi= 1000, lat_or_lon='lat')
plt.show()

AACGM_MLT Latitude from HALF_SLANT

# AACGM_MLT Lonngitude from Slant Ranges 
a = pydarn.RTP.plot_range_time(fitacf_data, beam_num=10,
                               zmin=-400, zmax=400, groundscatter=True,
                               range_estimation=pydarn.RangeEstimation.SLANT_RANGE,
                               coords=pydarn.Coords.AACGM_MLT, lat_or_lon='lon')
plt.savefig("AACGM_MLT 
AACGM_MLT Longitude from Slant Ranges
Longitude from Slant Ranges.png", dpi= 1000)
plt.show()

# AACGM_MLT Longitude from Range Gates 
a = pydarn.RTP.plot_range_time(fitacf_data, beam_num=10,
                               zmin=-400, zmax=400, groundscatter=True,
                               range_estimation=pydarn.RangeEstimation.RANGE_GATE,
                               coords=pydarn.Coords.AACGM_MLT, lat_or_lon='lon')
plt.savefig("AACGM_MLT Latitude from Range Gates.png", dpi= 1000)
plt.show()
AACGM_MLT longitude from Range Gates


# AACGM_MLT Longitude from GSMR
a = pydarn.RTP.plot_range_time(fitacf_data, beam_num=10,
                               zmin=-400, zmax=400, groundscatter=True,
                               range_estimation=pydarn.RangeEstimation.GSMR,
                               coords=pydarn.Coords.AACGM_MLT, lat_or_lon='lon')
plt.savefig("AACGM_MLT Longitude from GSMR.png", dpi= 1000)
plt.show()

AACGM_MLT Longitude from GSMR


# AACGM_MLT Longitude from HALF_SLANT
a = pydarn.RTP.plot_range_time(fitacf_data, beam_num=10,
                               zmin=-400, zmax=400, groundscatter=True,
                               range_estimation=pydarn.RangeEstimation.HALF_SLANT,
                               coords=pydarn.Coords.AACGM_MLT)
plt.savefig("AACGM_MLT Longitude from HALF_SLANT.png", dpi= 1000)
plt.show()


AACGM_MLT Longitude from HALF_SLANT


I will test summary plots shortly

**Comment by Shirling-VT** [comment]
@carleyjmartin I tested a few options for the summary plots, they all work fine for me. My major concern is that some of these conversions from km to geo or magnetic locations depends on time. The lat, lon in geographical coordinates may not be an issue since the conversion does not need time, but in magnetic coordinates, particularly MLT which is highly time dependent, if only using the provided start_time for the conversion, the results would look very confusing to me, since the radars are moving as the Earth rotates, but the backscatter local time won't change much with time in the current implementation. I don't have a better solution here, but think we should consider at least removing the MLT option if no better fix can be found. Hope my concern makes sense, feel free to let me know if people have a different opinion.

**Comment by carleyjmartin** [comment]
Thanks @Shirling-VT that was something I was wondering when I was working on this. The mag lat and lon use the date to be calculated but that changes on a pretty large timescale that I don't think we need to worry about it changing over a day of data for example, but MLT is definitely almost immediately wrong after the start date of a summary plot. I think the best option there is to remove it too, there's not really any way to have the correct MLT across the whole plot.

**Comment by carleyjmartin** [comment]
I'm going to close this and direct any interest to #331 which is a more up to date a better way to do this.

**Pull request closed without merging**
