### PR TITLE
Ehn/radars gate field

### PR DESCRIPTION
**Pull request by mts299**
# Scope 

I only did a 45 km will do 15 km later, got the value from recent fitacf files. 

**issue:** #130 

## Approval

**Number of approvals:** 1

## Test

``` python
pydarn.SuperDARNRadars.radars[1].range_gate_45
100
```

### CODE REVIEW

**Review by carleyjmartin — COMMENTED** [review]
Minor changes and one question that's only here because something else popped up in the changes for some reason that's not really related.

I just want to check, these are like a fall back value in case there is no value given from a data file (just plotting plain FOV/ data is from a grid file), and when a fitacf file is read in, if it has more than the given value here, the code later will take that into account and plot the FOV with the number of gates given in the fitacf file, if plotting a fan plot? 

I also thought that these values were going to be taken from the fov files when plotting rather than the hdw files as then when plotting a fov, it will never give an error? Then we only need to think about keeping the fov files up to date, rather than the files and these hardcoded values.

**Comment by Devin-Huyghebaert** [comment]
@carleyjmartin brings up some good points and questions for this code.  Are these values to be used as a default?  I do worry about hard coding in values, requiring a new release of pyDARN to change.

**Review by carleyjmartin — APPROVED** [review]
Where should be document that this is an interim fix whilst we work on rbpos?

**Comment by mts299** [comment]
Um I was gonnna add it to the FOV docs with rbpos added in so this could be merged and then we can do another full docs review on things as we now need to comment slant range and other things

**Comment by mts299** [comment]
@carleyjmartin is this good to be merged? Need to use it for rpos code  :p

**Pull request merged**
