### PR TITLE
Release pyDARN v3.1

### PR DESCRIPTION
**Pull request by carleyjmartin**
# Scope 

pyDARN release branch for v3.1 includes the following features:
- Full Cartopy coastline plotting options for all spatial plots
  - **NEW** `coastline` keyword in method calls
- Full Cartopy integration for plotting in geographic coordinates for grid and fan plots
- Completed polar coordinate convection maps including reference vector and many customization options
- Improved ACF plotting
- New `HALF_SLANT` range estimation for RTP
- **Bug fix** Multiple fan plots now available on one axis
- **Bug fix** `lowlat` keyword now available for geographic coordinate plots
- **Bug fix** Colorbars now extend/don't extend as required
along with many other minor improvements and bug fixes!

There is a PR not yet merged for the latitude and longitude y-axis options for RTPs, this is not vital but if you are interested in having this released alongside this release, please test that first and I can get it in here.

There is also updates to the documentation. To see those changes check out the read the docs here: https://pydarn.readthedocs.io/en/develop/

## Approval

**Number of approvals:** 3 or more, code review and testing for release
**DEADLINE: ~~21st NOV~~ 25th NOV**

## Test
**Note testers: please indicate what version of matplotlib you are using** - incredibly important as this branch includes a depreciation for matplotlib!

Please test as much as you can but especially:
- Grid plots (geographic, polar, coastlines)
- Fan plots (geo/polar, coastlines)
- Convection plots (polar only, all peripherials work, coastlines)
- ACF plots (new keywords and subplots)
- Range estimations in RTPs
- NEW CHANGE FROM REVIEWS - test read_hdw_files function.
- **Check you are on the zenodo json where you expect and with the correct information, let me know if there are any issues**

Please ask if you require any specific data formats to test!

### CODE REVIEW

**Comment by carleyjmartin** [comment]
Thanks @Shirling-VT !
I have updated the FOV and fan plot documentation with updated code and a few extra lines to describe plotting multiples in both of the coordinates.
I have build this branch in readthedocs so any updates will be here and not in develop now: https://pydarn.readthedocs.io/en/release-3.1/

I think we will probably go ahead with the release without the lon and lat for rtp plots as it has not been tested fully yet, we can get it in the next release.

**Comment by carleyjmartin** [comment]
To help with testing:

Here is a random selection of some fitacf, grid and map files I have around to use:
[fitgridmap.zip](https://github.com/SuperDARN/pydarn/files/10219268/fitgridmap.zip)
Here are some more fitacfs:
[fitacf.zip](https://github.com/SuperDARN/pydarn/files/10219303/fitacf.zip)
The rawacfs are a bit big for github so I've included one here, but can send others if need be:
[rawacf.zip](https://github.com/SuperDARN/pydarn/files/10219317/rawacf.zip)

Specific changes to test can be found in the top comment. If installing this branch independently with pip3 (recommend making virtual env to do this in first), I'd install the current release of pydarn `pip3 install pydarn` then uninstall `pip3 uninstall pydarn` as this will set up the dependencies for you, then install `pip3 install git+https://github.com/superdarn/pydarn@release/3.1` as installing branches by pip doesn't install the dependencies any longer. Or you can clone, checkout this branch and then `python3 setup.py install`. To test coastlines you will need to install cartopy independently: https://scitools.org.uk/cartopy/docs/latest/installing.html

There are code snippets to test with in the read the docs (also can see if the read the docs codes are working):
https://pydarn.readthedocs.io/en/release-3.1/

**Comment by RemingtonRohel** [comment]
Tested with the following settings on openSUSE Leap 15.3:

```
Package         Version     Location
--------------- ----------- ----------------------
aacgmv2         2.6.2
Cartopy         0.21.1
certifi         2022.12.7
contourpy       1.0.6
cycler          0.11.0
deepdish        0.3.7
fonttools       4.38.0
h5py            3.7.0
kiwisolver      1.4.4
matplotlib      3.6.2
numexpr         2.8.4
numpy           1.23.5
packaging       22.0
pathlib2        2.3.7.post1
Pillow          9.3.0
pip             21.1.2
pydarn          3.0         /home/remington/pydarn
pydarnio        1.2.0
pyparsing       3.0.9
pyproj          3.4.1
pyshp           2.3.1
python-dateutil 2.8.2
PyYAML          6.0
scipy           1.9.3
setuptools      57.0.0
shapely         2.0.0
six             1.16.0
tables          3.7.0
wheel           0.36.2
```

For grid plots, tested the following calls:

```python3
 pydarn.Grid.plot_grid(grid_data, start_time=stime)
pydarn.Grid.plot_grid(grid_data, start_time=stime, fov=False, lowlat=50)
pydarn.Grid.plot_grid(grid_data, start_time=stime, fov=True)
pydarn.Grid.plot_grid(grid_data, start_time=stime, coastline=True)
pydarn.Grid.plot_grid(grid_data, start_time=stime, coastline=True, parameter='wdt', lowlat=50)
pydarn.Grid.plot_grid(grid_data, start_time=stime, parameter='pwr', projs=pydarn.Projs.GEO, coords=pydarn.Coords.GEOGRAPHIC, coastline=True)
```

The last call failed, giving the following error:

```
/home/remington/pydarn/venv/bin/python /home/remington/pydarn/test_files/test_release3.1.py
resetting environment variable IGRF_COEFFS in python script
resetting environment variable AACGM_v2_DAT_PREFIX in python script
non-default coefficient files may be specified by running aacgmv2.wrapper.set_coeff_path before any other functions
        
IMPORTANT: Please make sure to cite pyDARN in publications that use plots created by pyDARN using DOI: https://zenodo.org/record/3727269. Citing information for SuperDARN data is found at https://pydarn.readthedocs.io/en/master/user/citing/
        
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

For map plotting, tested the following calls for north and south pole:

```python3
pydarn.Maps.plot_mapdata(map_data, record=15)
pydarn.Maps.plot_mapdata(map_data, record=15, parameter=pydarn.MapParams.RAW_VELOCITY, lowlat=50)
pydarn.Maps.plot_mapdata(map_data, record=15, parameter=pydarn.MapParams.MODEL_VELOCITY, len_factor=10)
pydarn.Maps.plot_mapdata(map_data, record=15, color_vectors=False, hmb=True, map_info=False, imf_dial=False)
pydarn.Maps.plot_mapdata(map_data, record=15, contour_fill=True, radar_location=True, coastline=True)
pydarn.Maps.plot_mapdata(map_data, record=15, coastline=True)
pydarn.Maps.plot_mapdata(map_data, record=15, parameter=pydarn.MapParams.SPECTRAL_WIDTH, boundary=True)
pydarn.Maps.plot_mapdata(map_data, record=15, parameter=pydarn.MapParams.POWER, contour_color='green')
```

The last two calls failed, with the following error messages:

```
/home/remington/pydarn/venv/bin/python /home/remington/pydarn/test_files/test_release3.1.py
resetting environment variable IGRF_COEFFS in python script
resetting environment variable AACGM_v2_DAT_PREFIX in python script
non-default coefficient files may be specified by running aacgmv2.wrapper.set_coeff_path before any other functions

IMPORTANT: Please make sure to cite pyDARN in publications that use plots created by pyDARN using DOI: https://zenodo.org/record/3727269. Citing information for SuperDARN data is found at https://pydarn.readthedocs.io/en/master/user/citing/
Traceback (most recent call last):
  File "/home/remington/pydarn/test_files/test_release3.1.py", line 123, in <module>
    test_map_plotting(map_files)
  File "/home/remington/pydarn/test_files/test_release3.1.py", line 94, in test_map_plotting
    pydarn.Maps.plot_mapdata(map_data, record=15, parameter=pydarn.MapParams.SPECTRAL_WIDTH, boundary=True)
  File "/home/remington/pydarn/pydarn/plotting/maps.py", line 321, in plot_mapdata
    plt.plot([mlons[-1], end_mlons[-1]],
UnboundLocalError: local variable 'end_mlons' referenced before assignment

Process finished with exit code 1
```

```
/home/remington/pydarn/venv/bin/python /home/remington/pydarn/test_files/test_release3.1.py
resetting environment variable IGRF_COEFFS in python script
resetting environment variable AACGM_v2_DAT_PREFIX in python script
non-default coefficient files may be specified by running aacgmv2.wrapper.set_coeff_path before any other functions

IMPORTANT: Please make sure to cite pyDARN in publications that use plots created by pyDARN using DOI: https://zenodo.org/record/3727269. Citing information for SuperDARN data is found at https://pydarn.readthedocs.io/en/master/user/citing/
Traceback (most recent call last):
  File "/home/remington/pydarn/test_files/test_release3.1.py", line 141, in <module>
    test_map_plotting(map_files)
  File "/home/remington/pydarn/test_files/test_release3.1.py", line 117, in test_map_plotting
    pydarn.Maps.plot_mapdata(map_data, record=15, parameter=pydarn.MapParams.POWER, contour_color='green')
  File "/home/remington/pydarn/pydarn/plotting/maps.py", line 321, in plot_mapdata
    plt.plot([mlons[-1], end_mlons[-1]],
UnboundLocalError: local variable 'end_mlons' referenced before assignment

Process finished with exit code 1
```

For ACF plotting, tested the following:

```python3
pydarn.ACF.plot_acfs(acf_data, beam_num=6, gate_num=31, start_time=stime)
pydarn.ACF.plot_acfs(acf_data, beam_num=6, gate_num=31, parameter='xcfd', normalized=True, start_time=stime)
pydarn.ACF.plot_acfs(acf_data, beam_num=6, gate_num=31, normalized=True, real_color='green', imaginary_color='purple', start_time=stime)
pydarn.ACF.plot_acfs(acf_data, beam_num=6, gate_num=31, plot_blank=False, start_time=stime)
pydarn.ACF.plot_acfs(acf_data, beam_num=6, gate_num=37, plot_blank=True, blank_marker='*', start_time=stime)
pydarn.ACF.plot_acfs(acf_data, beam_num=6, gate_num=31, pwr_and_phs=False, start_time=stime)
```

All worked as expected.

For Fitacf plotting, tried to test but wasn't able to read in any of the files that Carley provided. They all failed with the same error message:

```
/home/remington/pydarn/venv/bin/python /home/remington/pydarn/test_files/test_release3.1.py
resetting environment variable IGRF_COEFFS in python script
resetting environment variable AACGM_v2_DAT_PREFIX in python script
non-default coefficient files may be specified by running aacgmv2.wrapper.set_coeff_path before any other functions

IMPORTANT: Please make sure to cite pyDARN in publications that use plots created by pyDARN using DOI: https://zenodo.org/record/3727269. Citing information for SuperDARN data is found at https://pydarn.readthedocs.io/en/master/user/citing/
./fitgridmap/20220124.1200.00.sas.a.fitacf
./fitgridmap/20220124.1200.00.sps.a.fitacf
Error: The following fields in record 0 are missing: {'thr', 'rawacf.revision.minor', 'rawacf.revision.major'}
Error: The following fields in record 0 are missing: {'thr', 'rawacf.revision.minor', 'rawacf.revision.major'}

Process finished with exit code 0
```

**Comment by RemingtonRohel** [comment]
Made an error reading in fitacfs, all fitacf tests passed now for me.

**Comment by carleyjmartin** [comment]
Rem you're a gem. 💎 
First error is my fault, I gave you a bad grid file, it's got garbage data in it so I wouldn't expect it to work. Otherwise I can get the line to work with other files. Will attach some others if you want to check. The single radar grid I gave should work though.
I've pushed a commit to fix the other bug, turns out it was an issue trying to plot a reference vector for power and spectral width, both of which don't actually have vector values so it doesn't need a reference vector.
[20150308.south.grid2.bz2.zip](https://github.com/SuperDARN/pydarn/files/10221828/20150308.south.grid2.bz2.zip)

**Comment by tjk584** [comment]
Tested with following python packages on OpenSuSe 15.3:

```
Package            Version
------------------ -----------
aacgmv2            2.6.2
Cartopy            0.21.1
certifi            2022.12.7
charset-normalizer 2.1.1
click              8.1.3
conda              4.3.16
contourpy          1.0.6
cycler             0.11.0
deepdish           0.3.7
Flask              2.2.2
fonttools          4.38.0
h5py               3.7.0
idna               3.4
importlib-metadata 5.1.0
itsdangerous       2.1.2
Jinja2             3.1.2
kiwisolver         1.4.4
lxml               4.9.1
MarkupSafe         2.1.1
matplotlib         3.6.2
numexpr            2.8.4
numpy              1.23.5
packaging          22.0
pathlib2           2.3.7.post1
Pillow             9.3.0
pip                22.3.1
pycosat            0.6.3
pydarn             3.1
pydarnio           1.2.0
pyparsing          3.0.9
pyproj             3.4.1
pyshp              2.3.1
python-dateutil    2.8.2
PyYAML             6.0
requests           2.28.1
ruamel.yaml        0.17.21
ruamel.yaml.clib   0.2.7
scipy              1.9.3
setuptools         58.1.0
shapely            2.0.0
six                1.16.0
tables             3.7.0
urllib3            1.26.13
Werkzeug           2.2.2
wheel              0.38.4
zipp               3.11.0
```

### Grid plot Testing
Tested the following `plot_grid()` calls for files `20150301.2001.00.inv.grid` and `20150308.south.grid2`

```python
pydarn.Grid.plot_grid(grid_data, start_time=stime, projs=pydarn.Projs.POLAR)
pydarn.Grid.plot_grid(grid_data, start_time=stime, projs=pydarn.Projs.GEO, coords=pydarn.Coords.GEOGRAPHIC)
pydarn.Grid.plot_grid(grid_data, start_time=stime, projs=pydarn.Projs.POLAR, coords=pydarn.Coords.GEOGRAPHIC)
pydarn.Grid.plot_grid(grid_data, start_time=stime, projs=pydarn.Projs.POLAR, coastline=True)
pydarn.Grid.plot_grid(grid_data, start_time=stime, projs=pydarn.Projs.GEO, coords=pydarn.Coords.GEOGRAPHIC, coastline=True)
pydarn.Grid.plot_grid(grid_data, start_time=stime, coastline=True, lowlat=50, fov=False)
pydarn.Grid.plot_grid(grid_data, start_time=stime, projs=pydarn.Projs.GEO, coords=pydarn.Coords.GEOGRAPHIC, coastline=True, grid_lines=True, lowlat=50, fov=False)
```

Potential problems found:

- Field of view still appears on plots where `fov=False`
- Setting `projs=pydarn.Projs.POLAR` and `coords=pydarn.Coords.GEOGRAPHIC` results in data plotted outside the FOV shown on the plot (see below). This is probably intended, just thought I'd mention it as someone new to pyDARN
20150301 2001 00 inv grid gridtest3
- Plotting the `20150308.south.grid2` file with `projs=pydarn.Projs.GEO` and `coords=pydarn.Coords.GEOGRAPHIC` set results in a colourful hexagonal pattern surrounding the pole, see below:
20150308 south grid2 gridtest5
- I also noticed that `coords` and `projs` were defined in the Fan Plots additonal options within the ReadTheDocs, but not for Grid Plots or Convection Maps.


### Fan plot testing

Tested the following `plot_fan()` calls for the provided fitacf files:

```python
pydarn.Fan.plot_fan(fan_data, scan_index=5, projs=pydarn.Projs.POLAR, grid_lines=True)
pydarn.Fan.plot_fan(fan_data, scan_index=5, projs=pydarn.Projs.GEO, coords=pydarn.Coords.GEOGRAPHIC)
pydarn.Fan.plot_fan(fan_data, scan_index=5, projs=pydarn.Projs.POLAR, coords=pydarn.Coords.GEOGRAPHIC)
pydarn.Fan.plot_fan(fan_data, scan_index=5, projs=pydarn.Projs.POLAR, coastline=True, grid_lines=True)
pydarn.Fan.plot_fan(fan_data, scan_index=5, projs=pydarn.Projs.GEO, coords=pydarn.Coords.GEOGRAPHIC, coastline=True)
pydarn.Fan.plot_fan(fan_data, scan_index=5, projs=pydarn.Projs.POLAR, coastline=True, groundscatter=True, grid_lines=True, lowlat=50)
```

Potential problems found:

- grid lines don't appear on the FOV when `grid_lines=True` is set
- Setting `projs=pydarn.Projs.POLAR` and `coords=pydarn.Coords.GEOGRAPHIC` results in the data falling within the FOV, but the FOV is in a different location than the first two plots listed above


### Convection plot testing

Tested the following `plot_mapdata()` calls for the provided map files:

```python
pydarn.Maps.plot_mapdata(map_data, record=10)
pydarn.Maps.plot_mapdata(map_data, record=10, coastline=True)
pydarn.Maps.plot_mapdata(map_data, record=10, coastline=True, parameter=pydarn.MapParams.RAW_VELOCITY, lowlat=50)
pydarn.Maps.plot_mapdata(map_data, record=10, coastline=True, parameter=pydarn.MapParams.MODEL_VELOCITY, boundary=True, radar_location=True, hmb=False, imf_dial=False, map_info=False)
pydarn.Maps.plot_mapdata(map_data, record=10, coastline=True, parameter=pydarn.MapParams.SPECTRAL_WIDTH, hmb=True, contour_fill=True)
pydarn.Maps.plot_mapdata(map_data, record=10, coastline=True, parameter=pydarn.MapParams.POWER, len_factor=3, lowlat=10)
pydarn.Maps.plot_mapdata(map_data, record=10, coastline=True, hmb=True, contour_fill=True, len_factor=1, lowlat=10)
```

Potential problems found:

- Plotting with `parameter=pydarn.MapParams.POWER` and `parameter=pydarn.MapParams.SPECTRAL_WIDTH` failed with the following warning:
```
Traceback (most recent call last):
  File "/home/radar/testing/pyDARN_testing/release_3_1_test.py", line 101, in <module>
    pydarn.Maps.plot_mapdata(map_data, record=10, coastline=True, parameter=pydarn.MapParams.SPECTRAL_WIDTH, hmb=True, contour_fill=True)
  File "/home/radar/pydarn-env/lib64/python3.9/site-packages/pydarn/plotting/maps.py", line 321, in plot_mapdata
    plt.plot([mlons[-1], end_mlons[-1]],
UnboundLocalError: local variable 'end_mlons' referenced before assignment
```

### ACF plot testing

Tested the following `plot_acfs()` calls for the provided rawacf files:

```
pydarn.ACF.plot_acfs(acf_data, beam_num=6, gate_num=44, start_time=st)
pydarn.ACF.plot_acfs(acf_data, beam_num=6, gate_num=44, start_time=st, normalized=True, plot_blank=False)
pydarn.ACF.plot_acfs(acf_data, beam_num=6, gate_num=16, start_time=st, parameter="xcfd")
pydarn.ACF.plot_acfs(acf_data, beam_num=6, gate_num=44, pwr_and_phs=False, scan_num=50)
```

These tests passed with no errors, and the plots looked good

**Comment by carleyjmartin** [comment]
With ~3 tests and some new commits done, I'm going to aim to do some final testing and release this next week. Let me know if anyone wants more time to test!
Again, make sure your orcid/name/affil is correct in the zenodo json please! :)

**Pull request merged**
