### PR TITLE
FIX: New setup for installation/hdw repo not installing fix

### LINKED ISSUE #292: BUG: hdw repo not being cloned on install
# BUG 

I've had a few reports of the hdw repository not being downloaded on install. 
I can recreate this error, but only when trying to install system wide.

Until a solution is made I recommend that if you find this error you can try:
1. Installing and running pyDARN programs in a virtual environment https://docs.python.org/3/library/venv.html
2. Cloning the hdw repository in the `utils` directory of wherever pyDARN has installed https://github.com/SuperDARN/hdw

If you do find this error, please comment with the traceback, and so that I know if it's widespread or os dependent. 

## Priority

- [ ] Minor - typo, incorrect naming, fails on specific uncommon situation
- [x] Major - misrepresentation of data, failure in a common situation 
- [ ] Urgent - failure in usage, large misrepresentation

## Information
**python version**: 3.10
**OS**: MacOS Monterey
**matplotlib version**: NA

## Example of the bug 

Occurs on `import pydarn` on new install. 

### Attempts

*What have you tried already to fix it?*
NA

*What have you tried to get around it?*
See above for solutions in the meantime. 

## Potential Bug Location 

On install during hdw repo cloning. 

## Potential Solution(s)

Any ideas welcome.

### PR DESCRIPTION
**Pull request by carleyjmartin**
# Scope 

This PR fixes the installation issue which misses the hdw repo.
Also includes updates to avoid issues due to depreciation of things in setuptools.
All thanks for fix to @RemingtonRohel 
Documentation on setuptools and setup.py can be found here: https://setuptools.pypa.io/en/latest/userguide/package_discovery.html
Spoilers, the docs are pretty unhelpful, so also linked below is an article about moving to pyproject.toml if anyone is really interested: https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html

**issue:** close #292 

## Approval

**Number of approvals:** 2 (installation instructions below)

## Test

Please install using the test installation via testpypi (https://test.pypi.org/project/pydarn/):
`pip install -i https://test.pypi.org/simple/ pydarn`
Don't worry about the version #, it is still 3.1, I just had to give it different versions to upload to testpypi.

**Then please plot whatever you would normally plot and make sure it's all there and working as you expect.**

You can check that the hdw repo is installed by checking in the utils package wherever python has installed the package. E.G. I installed in a virtual env so:
```
>>> import sys
>>> sys.path
>>> ['/Users/carley/Documents/venv/lib/python3.10/site-packages']
```
Hence my hdw rep will be in `/Users/carley/Documents/venv/lib/python3.10/site-packages/pydarn/utils`

**If you have errors please post the full traceback with `-v / -verbose` option if possible**

### CODE REVIEW

**Comment by tjk584** [comment]
Tested installing within a fresh virtual environment, and got the following error:

```console
(test_venv) radar@labborealis:~/testing/pyDARN_testing/pr_299> pip install --verbose -i https://test.pypi.org/simple/ pydarn
Using pip 22.0.4 from /home/radar/testing/pyDARN_testing/pr_299/test_venv/lib64/python3.9/site-packages/pip (python 3.9)
Looking in indexes: https://test.pypi.org/simple/
Collecting pydarn
  Downloading https://test-files.pythonhosted.org/packages/48/12/e634b9349fef9d2bd31aa41bf6fca31a97602c0f17763b7057791e6abbbf/pydarn-3.1.101-py3-none-any.whl (105 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.1/105.1 KB 640.4 kB/s eta 0:00:00
Collecting pyyaml
  Downloading https://test-files.pythonhosted.org/packages/3a/09/50cff727ed4679924f3994c69a1fa27405a69a40038dc71b47204746ad2d/PyYAML-3.11.tar.gz (138 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 138.4/138.4 KB 1.8 MB/s eta 0:00:00
  Running command python setup.py egg_info
  running egg_info
  creating /tmp/pip-pip-egg-info-0eb9xa6b/PyYAML.egg-info
  writing /tmp/pip-pip-egg-info-0eb9xa6b/PyYAML.egg-info/PKG-INFO
  writing dependency_links to /tmp/pip-pip-egg-info-0eb9xa6b/PyYAML.egg-info/dependency_links.txt
  writing top-level names to /tmp/pip-pip-egg-info-0eb9xa6b/PyYAML.egg-info/top_level.txt
  writing manifest file '/tmp/pip-pip-egg-info-0eb9xa6b/PyYAML.egg-info/SOURCES.txt'
  error: package directory 'lib3/yaml' does not exist
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /home/radar/testing/pyDARN_testing/pr_299/test_venv/bin/python3 -c '
  exec(compile('"'"''"'"''"'"'
  # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
  #
  # - It imports setuptools before invoking setup.py, to enable projects that directly
  #   import from `distutils.core` to work with newer packaging standards.
  # - It provides a clear error message when setuptools is not installed.
  # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
  #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
  #     manifest_maker: standard file '"'"'-c'"'"' not found".
  # - It generates a shim setup.py, for handling setup.cfg-only projects.
  import os, sys, tokenize
  
  try:
      import setuptools
  except ImportError as error:
      print(
          "ERROR: Can not execute `setup.py` since setuptools is not available in "
          "the build environment.",
          file=sys.stderr,
      )
      sys.exit(1)
  
  __file__ = %r
  sys.argv[0] = __file__
  
  if os.path.exists(__file__):
      filename = __file__
      with tokenize.open(__file__) as f:
          setup_py_code = f.read()
  else:
      filename = "<auto-generated setuptools caller>"
      setup_py_code = "from setuptools import setup; setup()"
  
  exec(compile(setup_py_code, filename, "exec"))
  '"'"''"'"''"'"' % ('"'"'/tmp/pip-install-b_y4knyt/pyyaml_699b93e945584f42be7d25c20d6c9d1d/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' egg_info --egg-base /tmp/pip-pip-egg-info-0eb9xa6b
  cwd: /tmp/pip-install-b_y4knyt/pyyaml_699b93e945584f42be7d25c20d6c9d1d/
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by carleyjmartin** [comment]
There are some issues with testpypi installing dependencies, so if you're installing in a fresh venv I'd `pip3 install pydarn` and then `pip3 uninstall pydarn` to get the dependencies, then install as above. I'm not sure how to get around this, you can just manually install each dependency it comes up against too.

**Review by tjk584 — APPROVED** [review]
After following Carley's instructions, I was able to successfully install pydarn via testpypi. Performed the following tests on OpenSuSe 15.3:

- verified that the `hdw/` repo was installed within the `pydarn/utils/` directory
- compared map, grid, fan, and acf plots created with a different version of pyDARN and verified they looked the same

**Comment by KhanalKrishna** [comment]
Hi,
It is working as expected for me. I checked fan and grid plots after installing pydarn this way.

**Comment by carleyjmartin** [comment]
With two successful installations, I'll merge this today. Likely try to do a patch release for this early next week as it is a major problem for installing. Will make issue for patch release today.

**Pull request merged**
