### PR TITLE
New Feature: HALF_SLANT option for RangeEstimate

### PR DESCRIPTION
**Pull request by carleyjmartin**
# Scope 

This PR adds an option to plot *HALF_SLANT* in fan plots and range time plots. Half slant is equal to *SLANT_RANGE* options divided by 2. This is considered better(?) than using GSMR option. 
 https://doi.org/10.1029/2022RS007429

**issue:** #273 

## Approval

**Number of approvals:** 2 please, lots of plotting testing

## Test

**matplotlib version**: 3.5.2
**Note testers: please indicate what version of matplotlib you are using**

Summary plots:
```python
import matplotlib.pyplot as plt 
import pydarn

file = "/Users/carley/Documents/data/20131031.2201.00.sas.fitacf"
SDarn_read = pydarn.SuperDARNRead(file)
fitacf_data = SDarn_read.read_fitacf()

a = pydarn.RTP.plot_summary(fitacf_data, beam_num=2, range_estimation=pydarn.RangeEstimation.HALF_SLANT)
plt.show()
```
Gives: 
Screen Shot 2022-08-04 at 9 38 57 AM

Fan plots (comparison with SLANT_RANGE):
```python
import matplotlib.pyplot as plt
import pydarn

file='/Users/carley/Documents/data/20150308.1400.03.cly.fitacf'
SDarn_read = pydarn.SuperDARNRead(file)
fitacf_data = SDarn_read.read_fitacf()

# Half Slant
pydarn.Fan.plot_fan(fitacf_data, scan_index=5,
                    radar_label=True, lowlat=50,
                    range_estimation=pydarn.RangeEstimation.HALF_SLANT)
plt.show()

# Slant range
pydarn.Fan.plot_fan(fitacf_data, scan_index=5,
                    radar_label=True, lowlat=50)
plt.show()
```
Gives:

Screen Shot 2022-08-04 at 9 22 08 AM
Screen Shot 2022-08-04 at 9 22 23 AM

### CODE REVIEW

**Comment by bharatreddy** [comment]
For better documentation purposes, can someone please elaborate on how the Thomas et al., [2022] study (https://doi.org/10.1029/2022RS007429) suggests that HALF_SLANT is better than GSMR?

**Comment by bharatreddy** [comment]
In fan plots, along with the backscatter the field-of-view of the radar changes (reduces by half). Should we keep the field-of-view constant and only change the location of the backscatter? This is not necessarily a problem though.

**Comment by w2naf** [comment]
Hi Bharat,

I would imagine we should cut the field of view in half, too. If you are dividing all of the ranges by half, then that in effect reduces the theoretical size of the FOV as well.

**Comment by bharatreddy** [comment]
Thanks for the confirmation Nathaniel!

**Comment by w2naf** [comment]
You're welcome!

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by bharatreddy** [comment]
@carleyjmartin: I could successfully generate a bunch of scan and RTI plots using this functionality (for mid, high, polar radars). I'll do some more testing this week.

**Review by francistee26 — APPROVED** [review]
Hello @carleyjmartin I just tested your changes and everything seems to be working as intended for me.

**Pull request merged**
