### PR TITLE
EHN: Coastline options for Fan, FOV, Grid and Convection in projections.py

### PR DESCRIPTION
**Pull request by carleyjmartin**
# Scope 

This PR adds the keyword and option to include coastlines within the projections.py module. This allows all of the plotting modules to access the option and neatly keeps all the cartopy use within one module.  Default is set to coastline=False. similar to the draft PR for convection maps, there is little we can do to customise the coastlines.

**issue:** #248 (I think this solves this issue, but there might be other functions included for this)

## Approval

**Number of approvals:** 2

## Test
Please test for Fan, FOV, Grid and Convection plots!  Fan and FOV will plot coastlines for both Coords.GEOGRAPHIC and Coords.AACGM_MLT, grid and convection maps are only offered in MLT at the moment. Don't forget to test for southern data too!
**matplotlib version**: 3.5.2
**Note testers: please indicate what version of matplotlib you are using**

*Fan plot:*
```python
import matplotlib.pyplot as plt
import pydarn
file='/Users/carley/Documents/data/20150308.1400.03.cly.fitacf'
SDarn_read = pydarn.SuperDARNRead(file)
fitacf_data = SDarn_read.read_fitacf()

# Geographic
pydarn.Fan.plot_fan(fitacf_data, fov_color='red', scan_index=5,
                    radar_label=True, groundscatter=True,
                    coords=pydarn.Coords.GEOGRAPHIC ,projs=pydarn.Projs.GEO,
                    coastline=True)
plt.show()

# MLT
pydarn.Fan.plot_fan(fitacf_data, grid=True, scan_index=5, radar_label=True,
                    groundscatter=True, coastline=True)
plt.show()
```
Screen Shot 2022-05-20 at 12 15 53 PM
Screen Shot 2022-05-20 at 12 16 05 PM

*Grids*
```python
import matplotlib.pyplot as plt 
import pydarn

grid_file = "/Users/carley/Documents/data/grids/20011220.8000.grid"
grid_data = pydarn.SuperDARNRead(grid_file).read_grid()

fanplot = pydarn.Grid.plot_grid(grid_data, parameter = 'vel', 
                radar_label=True, radar_location=True, fov_color='grey', 
                lowlat=30, coastline=True)
plt.show()
```
Screen Shot 2022-05-20 at 12 17 37 PM

*Convection maps:*
```python
import matplotlib.pyplot as plt
import pydarn

#map_file = "/Users/carley/Documents/data/maps/20150310.n.map"
map_file = "/Users/carley/Documents/data/maps/20170113.s.map"
#map_file = "/Users/carley/Documents/data/maps/20190421.s.map2"
map_data = pydarn.SuperDARNRead().read_dmap(map_file)

pydarn.Maps.plot_mapdata(map_data,record=360, 
            parameter=pydarn.MapParams.FITTED_VELOCITY,
            lowlat=40, coastline=True)
plt.show()
```
Screen Shot 2022-05-20 at 12 18 09 PM

### CODE REVIEW

**Review by billetd — APPROVED** [review]
Looks good to me.

**Comment by carleyjmartin** [comment]
Fixed merge conflicts with the ax bug fix. Please test to make sure I didn't mess up the merge! :)

**Comment by Shirling-VT** [comment]
@carleyjmartin @billetd @bharatreddy I couldn't add the coastlines using the test codes, need another person to test and confirm.

**Comment by KhanalKrishna** [comment]
image

I could not get the coastlines on convection map. I used .map2 file.

**Comment by carleyjmartin** [comment]
Hey! Yes, you'll need to use this branch which is `ehn/fan_mag_coastline`
You can clone the repo, checkout this branch and install (python3 setup.py install)
Or, I find it easier to make a virtual env and then install with `pip3 install git+https://github.com/superdarn/pydarn@ehn/fan_mag_coastline`
But that second way you'll also have to do the pip3 installs for cartopy again in the venv.

**Pull request merged**
