### PR TITLE
BUG: Fix for when colour bars should not be extended below zero

### PR DESCRIPTION
**Pull request by carleyjmartin**
# Scope 

This PR changes the colour bar plotting for rtp, fan, grid and map plots where the colour map does not extend below zero. 
This is done by having an if statement around the colour bar plotting, if the vmin of the data is == 0 then only extend the top of the bar, if not then have both extended. 

I have not changed the code for contour colour bar in maps as the contours will always be centred at 0 so extend both ways regardless. 

**issue:** No issue made

## Approval

**Number of approvals:** 2

## Test

**matplotlib version**: 3.5.3
**Note testers: please indicate what version of matplotlib you are using**

```python
import matplotlib.pyplot as plt 
import pydarn

# RTP and Fan
file = "/Users/carley/Documents/data/20160120.1602.00.cly.fitacf"
SDarn_read = pydarn.SuperDARNRead(file)
fitacf_data = SDarn_read.read_fitacf()

a = pydarn.RTP.plot_summary(fitacf_data, beam_num=10,
                            range_estimation=pydarn.RangeEstimation.RANGE_GATE)
plt.show()

pydarn.Fan.plot_fan(fitacf_data, scan_index=50,
                    radar_label=True, lowlat=50, parameter='p_l')
plt.show()

# Grid Plot
grid_file = "/Users/carley/Documents/data/grids/20011220.8000.grid"
grid_data = pydarn.SuperDARNRead(grid_file).read_grid()
pydarn.Grid.plot_grid(grid_data, record=5, parameter = 'vel',
                      fov_color='grey')
plt.show()

# Convection Map
map_file = "/Users/carley/Documents/data/maps/20150310.n.map"
map_data = pydarn.SuperDARNRead().read_dmap(map_file)
pydarn.Maps.plot_mapdata(map_data,record=360, 
            parameter=pydarn.MapParams.FITTED_VELOCITY,
            lowlat=50)
plt.show()
```
Screen Shot 2022-08-18 at 4 29 43 PM
Screen Shot 2022-08-18 at 4 30 01 PM
Screen Shot 2022-08-18 at 4 30 15 PM
Screen Shot 2022-08-18 at 4 32 00 PM

### CODE REVIEW

**Comment by Shirling-VT** [comment]
It works when we use the default Zmin or set it to 0, but if someone set Zmin to below zero, then the bar would still extend below this Zmin value. This does not make sense for the vector plot, but not sure for the fan plot which one is more reasonable, since there are times we do have negative spectral width data for some reason. We can discuss it during our dev meeting this week.

#MacOS Monterey 12.5.1 
#matplotlib 3.4.2
#python 3.8.0

a = pydarn.Fan.plot_fan(fitacf_data, scan_index=50,zmin=-10,zmax=50,
                        radar_label=True, lowlat=50, parameter='p_l')
plt.show()

image

# Convection Map
map_file = '/Users/xueling/data/superdarn/2015/map2/north/20150310.north.map2.bz2'
map_data = pydarn.SuperDARNRead().read_dmap(map_file)
pydarn.Maps.plot_mapdata(map_data,record=360,zmin=-100,zmax=1000,
            parameter=pydarn.MapParams.FITTED_VELOCITY,
            lowlat=50)
plt.show()

image

**Comment by carleyjmartin** [comment]
I guess for the convection maps, the zmin shouldn't be set as a negative anyway in most cases, obviously the code allows this but the user should have some understanding of the data to know this I hope. 

For the fan plots, the data for velocity even if zmin is set to 0 would still extend below zero, but the cb would not, but again with the diverging red/blue color bar I'm hoping the user understands they should be putting in +- numbers for the limits for this specifically.

My idea of setting the bar to not extend if the zmin = 0 was the easiest way I could think of to encompass everything without having 7 `if/else parameter == something` statements just for the color bars. But I agree it does give the user some room to make some errors, I'm unsure how to solve this effectively and without bloat really - unless - we just let the user decide and add the kwarg for `extend` as an option in plotting, then the user themselves can decide if they want "both", "min", "max" or "neither"? I don't think that would be easy to do for the summary plots though with four cb, only 1 of them is extended to "both" without hard coding it the same way as this PR.

(But yeah we can discuss it tomorrow! I'm just writing some ideas/pros/cons down now or i'll forget!)

**Comment by KhanalKrishna** [comment]
Matplotlib version: 3.5.1

file = "20180225.1801.00.rkn.fitacf"
SDarn_read = pydarn.SuperDARNRead(file)
fitacf_data = SDarn_read.read_fitacf()

a = pydarn.RTP.plot_summary(fitacf_data, beam_num=10,
                            range_estimation=pydarn.RangeEstimation.RANGE_GATE)
plt.show()

image

pydarn.Fan.plot_fan(fitacf_data, scan_index=50,
                    radar_label=True, lowlat=50, parameter='p_l')
plt.show()

image

# Grid Plot
grid_file = "test.grd"
grid_data = pydarn.SuperDARNRead(grid_file).read_grid()
pydarn.Grid.plot_grid(grid_data, record=5, parameter = 'vel',
                      fov_color='grey')
plt.show()

image


# Convection Map
map_file = "20121101-21-02-north.txt"
map_data = pydarn.SuperDARNRead().read_dmap(map_file)
pydarn.Maps.plot_mapdata(map_data,record=200, 
            parameter=pydarn.MapParams.FITTED_VELOCITY,
            lowlat=50)
plt.show()

convection map could not be generated using the branch bug/colbar-ends.

**Comment by carleyjmartin** [comment]
@KhanalKrishna 
Was there any error with the convection maps? You should be able to plot them on this branch.

**Comment by KhanalKrishna** [comment]
@carleyjmartin , sorry I used wrong file. I am updating my previous comment.

**Comment by carleyjmartin** [comment]
Feel free to merge, I think that's two reviews done :)

**Comment by KhanalKrishna** [comment]
Did it. Thank you. This was my first-ever merge :)

**Pull request merged**
