### PR TITLE
TEST: Update pytest suite

### PR DESCRIPTION
**Pull request by carleyjmartin**
# Scope 

This PR includes a new test for map plotting, and updates other plotting tests with new parameters if required.

**issue:** No issue made

## Approval

**Number of approvals:** 1

## Test

**matplotlib version**: 3.3.4 (NOTE THAT version 3.6.0 will cause an error, see #284 for fix, you will have to downgrade matplotlib to test until that fix is merged)
**Note testers: please indicate what version of matplotlib you are using**

To test the test suite, you will need to install pytest, clone the repo, checkout this branch, install pydarn, and run 'pytest'. I would recommend doing this in a virtual environment.
Virtual env (3.10+):
```
python3 -m venv venv-testsuite  
source venv-testsuite/bin/activate
```
you can use `python3 -m virtualenv venv-testsuite` for <3.10

Testing:
```
pip3 install pytest
git clone https://github.com/SuperDARN/pydarn.git
cd pydarn
git checkout test/update_testsuite
python3 setup.py install (or however you like to install a branch)
pytest
```

It will then run a series of tests on each plot, little green dots will appear as it goes and you'll end up with something like:
```
test/test_Fan.py ................................................                                               [  7%]
test/test_Grid.py .....................                                                                         [ 11%]
test/test_RTP.py .............................................................................................. [ 26%]
............................................................................................................... [ 44%]
............................................................................................................... [ 63%]
............................................................................................................... [ 81%]
........................................................................................................        [ 98%]
test/test_maps.py ...........                                                                                   [100%]

==================================== 611 passed, 12 warnings in 168.94s (0:02:48) =====================================

```
Don't worry about the warnings.
Let me know if any fail! It will give you the error traceback for any failures above the line above, please copy those into a comment if you find any do fail, thanks!

The test suite will not test for anything Cartopy related so a few parameters are not tested here.

### CODE REVIEW

**Comment by KhanalKrishna** [comment]
Hi @carleyjmartin,
I have the following:
image

**Comment by carleyjmartin** [comment]
Thanks for testing, see the matplotlib note at the top, there's a PR out to fix it already, you'll need to downgrade matplotlib to test.

**Comment by KhanalKrishna** [comment]
Thank you @carleyjmartin. Success.
image

**Comment by carleyjmartin** [comment]
Feel free to merge, the testing module isn't shipped with releases so it's only useful to us devs so I assume one tester is fine for this. :)

**Pull request merged**
