### PR TITLE
Ehn/virtual height modularization

### PR DESCRIPTION
**Pull request by francistee26**
# Scope 

This pull request enables pydarn with the modularization of virtual heights which include the standard virtual height and chisham virtual height. A new empirical virtual height model by G. Chisham 2008 (https://angeo.copernicus.org/articles/26/823/2008/)

## Approval

**Number of approvals:** 2

## Test
```
from pydarn.utils.virtual_heights_types import VH_types
from pydarn.utils.virtual_heights import standard_virtual_height, chisham

slant_range = 157.5
cell_height = 300

virtual_height_type = VH_types.CHISHAM
if virtual_height_type == VH_types.CHISHAM:
    x_height = chisham(slant_range)
    print(f"Chisham Virtual Height:{x_height}")
    
virtual_height_type = VH_types.STANDARD_VIRTUAL_HEIGHT    
if virtual_height_type == VH_types.STANDARD_VIRTUAL_HEIGHT:
    x_height = standard_virtual_height(slant_range, cell_height)
    print(f"Standard Virtual Height:{x_height}")
```

### CODE REVIEW

**Review by carleyjmartin — CHANGES_REQUESTED** [review]
Just testing, no code review: No issue on install, no issue running provided code. 

It appears that the changes made do not allow any of the plotting methods (e.g. `plot_summary` and `plot_fan`) to work without overriding the coords default, which is now AACGM. 
There also seems to be a reappearance of all the variables that are carried through with **kwargs. I think this might be because the code was amended from code before we did that? I would suggest either merging with develop or making the changes from the current develop branch.

MPL version: 3.4.3

**Comment by francistee26** [comment]
> Just testing, no code review: No issue on install, no issue running provided code.
> 
> It appears that the changes made do not allow any of the plotting methods (e.g. `plot_summary` and `plot_fan`) to work without overriding the coords default, which is now AACGM.
> There also seems to be a reappearance of all the variables that are carried through with **kwargs. I think this might be because the code was amended from code before we did that? I would suggest either merging with develop or making the changes from the current develop branch.
> 
> MPL version: 3.4.3

Hi @carleyjmartin sorry for the late response I will try to look at those issues.

**Comment by Shirling-VT** [comment]
No issue on install, no issue running provided code. Returned results: Chisham Virtual Height:113.644277766875; Standard Virtual Height:115.

**Comment by francistee26** [comment]
> Just testing, no code review: No issue on install, no issue running provided code.
> 
> It appears that the changes made do not allow any of the plotting methods (e.g. `plot_summary` and `plot_fan`) to work without overriding the coords default, which is now AACGM.
> There also seems to be a reappearance of all the variables that are carried through with **kwargs. I think this might be because the code was amended from code before we did that? I would suggest either merging with develop or making the changes from the current develop branch.
> 
> MPL version: 3.4.3

@carleyjmartin I just checked on my end and everything works I am not sure why you are having issues.

**Comment by carleyjmartin** [comment]
@francistee26 Do you have an example of how to use the `plot_summary` method for example, one of the specific examples I can't get to work is:
```
import matplotlib.pyplot as plt 
import pydarn

file = "/Users/carley/Documents/data/20150305.0601.00.inv.fitacf"

SDarn_read = pydarn.SuperDARNRead(file)
fitacf_data = SDarn_read.read_fitacf()

a = pydarn.RTP.plot_summary(fitacf_data, beam_num=2, coords=pydarn.Coords.GROUND_SCATTER_MAPPED_RANGE)
plt.show()
```

I get the error:
```
Traceback (most recent call last):
  File "slant_test.py", line 15, in <module>
    a = pydarn.RTP.plot_summary(fitacf_data, beam_num=2, coords=pydarn.Coords.GROUND_SCATTER_MAPPED_RANGE)
  File "/Users/carley/Documents/testing_code/venv-vhm/lib/python3.7/site-packages/pydarn/plotting/rtp.py", line 1116, in plot_summary
    **kwargs)
  File "/Users/carley/Documents/testing_code/venv-vhm/lib/python3.7/site-packages/pydarn/plotting/rtp.py", line 369, in plot_range_time
    y = y[y0inx:]
IndexError: invalid index to scalar variable.
```

So I'm assuming there is some more options I need to give the method to make the ground scatter mapped range or slant range work? I've tried using a `virtual_height_type` option.  
But running with that doesn't like the `virtual_height_type` input. Also tried adding a `reflection_height` but to no avail.
Do you have examples of how to use `plot_fan` and `plot_fov` as I'm getting various different errors from trying to use those too. I can post copies of the errors, but don't want to overload the one comment if it's just that I don't know how to use the new inputs for the methods.

**Comment by francistee26** [comment]
> EDIT: Was this meant to be merged earlier?
> 
> @francistee26 Do you have an example of how to use the `plot_summary` method for example, one of the specific examples I can't get to work is:
> 
> ```
> import matplotlib.pyplot as plt 
> import pydarn
> 
> file = "/Users/carley/Documents/data/20150305.0601.00.inv.fitacf"
> 
> SDarn_read = pydarn.SuperDARNRead(file)
> fitacf_data = SDarn_read.read_fitacf()
> 
> a = pydarn.RTP.plot_summary(fitacf_data, beam_num=2, coords=pydarn.Coords.GROUND_SCATTER_MAPPED_RANGE)
> plt.show()
> ```
> 
> I get the error:
> 
> ```
> Traceback (most recent call last):
>   File "slant_test.py", line 15, in <module>
>     a = pydarn.RTP.plot_summary(fitacf_data, beam_num=2, coords=pydarn.Coords.GROUND_SCATTER_MAPPED_RANGE)
>   File "/Users/carley/Documents/testing_code/venv-vhm/lib/python3.7/site-packages/pydarn/plotting/rtp.py", line 1116, in plot_summary
>     **kwargs)
>   File "/Users/carley/Documents/testing_code/venv-vhm/lib/python3.7/site-packages/pydarn/plotting/rtp.py", line 369, in plot_range_time
>     y = y[y0inx:]
> IndexError: invalid index to scalar variable.
> ```
> 
> So I'm assuming there is some more options I need to give the method to make the ground scatter mapped range or slant range work? I've tried using a `virtual_height_type` option.
> But running with that doesn't like the `virtual_height_type` input. Also tried adding a `reflection_height` but to no avail.
> Do you have examples of how to use `plot_fan` and `plot_fov` as I'm getting various different errors from trying to use those too. I can post copies of the errors, but don't want to overload the one comment if it's just that I don't know how to use the new inputs for the methods.

Hi @carleyjmartin I did not make any changes to the method pydarn.RTP.plotSummary and I don't recall ever using it myself, but I know the plot_fan method I worked on works. I can try to look at the pydarn.RTP.plotSummary method when I have time this weekend and see what's causing the error.

**Comment by francistee26** [comment]
> Hey @francistee26 : the plot_summary method calls the range time, time series and all the axes/labels methods and radar_pos too, so no direct changes were made in the plot_summary method, but the changes in radar_pos seem to be having a knock on effect in the plot_summary and plot_rangetime methods. I think plot time series is fine as it doesn't use radar_pos? I can have a deeper look into the errors, but will take me longer as I'm not familiar with the newer parts of the code.
> 
> Do you have example code for working plot_fan so I can figure out where I'm going wrong on that one?

Sorry for the late response again @carleyjmartin check my branch that @mts299  shared with you.

**Pull request merged**
