### PR TITLE
EHN: Grid key word in FOV to plot the grid of gates and beams

### PR DESCRIPTION
**Pull request by carleyjmartin**
# Scope 

This PR adds the ability to plot all gate and beam boundaries on a FOV or Fan plot using the key word `grid`.
`grid` is defaulted to False, as it's a lot of lines and can look messy especially when plotting data. I have also set the inner lines to have 0.2 width, this seems to look a bit cleaner than the 0.5 lines because there are so many of them.

**issue:**  no linked issue, but mentioned in closed PR #183 

## Approval

**Number of approvals:** 2 (test and code review)

## Test

**matplotlib version**:  3.4.2
**Note testers: please indicate what version of matplotlib you are using**

pytest was run but not modified, no failures

Example of FOV plotting:
```python
import pydarn
from datetime import datetime
import matplotlib.pyplot as plt 

fanplot=pydarn.Fan.plot_fov(66, datetime(2021, 2, 5, 12, 5), radar_location=True, radar_label=True, lowlat= 50,boundary=True, line_color='red', grid = True)
fanplot1=pydarn.Fan.plot_fov(5, datetime(2021, 2, 5, 12, 5), radar_location=True, radar_label=True,  ax=1, boundary=True, line_color='blue', grid = True)
fanplot2=pydarn.Fan.plot_fov(64, datetime(2021, 2, 5, 12, 5), radar_location=True, radar_label=True,  ax=1, boundary=True, line_color='green', grid = True)
fanplot3=pydarn.Fan.plot_fov(65, datetime(2021, 2, 5, 12, 5), radar_location=True, radar_label=True,  ax=1, boundary=True, line_color='orange', grid = True)
fanplot4=pydarn.Fan.plot_fov(6, datetime(2021, 2, 5, 12, 5), radar_location=True, radar_label=True,  ax=1, boundary=True, grid = True)
plt.show()
```
Screen Shot 2021-09-08 at 1 34 55 PM

Example of Fan plotting:
```python
import matplotlib.pyplot as plt
import pydarn
import datetime as dt

#Read in fitACF file
file = "/Users/carley/Documents/data/20150305.0601.00.inv.fitacf"
SDarn_read = pydarn.SuperDARNRead(file)
fitacf_data = SDarn_read.read_fitacf()

time = dt.datetime(2015,3,5,6,5)
fanplot = pydarn.Fan.plot_fan(fitacf_data, scan_index=time,
                    colorbar_label='Velocity [m/s]',zmin=-2000, zmax=2000, lowlat=50, groundscatter=True, grid=True)            
plt.show()
```
Screen Shot 2021-09-08 at 12 52 02 PM

### CODE REVIEW

**Comment by mts299** [comment]
Curious is there a way to pass an alpha for the data coloring and the lines. The lines seem more predominant. 

Also, can you add pytest for the new parameter?

**Comment by mts299** [comment]
Code works for me

**Review by mts299 — APPROVED** [review]

**Comment by carleyjmartin** [comment]
Added a line_alpha key word, with default of 0.5 which sets the alpha for all the lines. I didn't want to use the same alpha key word as the fill option, so made a new one. Here's an example of the default look: 
Screen Shot 2021-09-10 at 1 38 24 PM
Both keywords added to pytest too.

**Comment by mts299** [comment]
Works and looks good to me for `pytest`

**Pull request merged**
