### PR TITLE
[PATCH] pyDARN v2.1.1

### PR DESCRIPTION
**Pull request by mts299**
# Scope 

Patch release for the major 3 bug fixes: 
- ground scatter miss interpretation 
- `plot_fan` `scan_index` not working with `int` input
- time shifting in range-time plots 
- `time_series` taking vector parameters `p_l` `v` `w_l`
 
**issue:** #177 

## Approval 

**Number of approvals:** *3* approvals as per usual 

**Deadline** 

## Test

- [ ] RTP testing
- [ ] time series with a vector parameter
- [ ] Fan plot testing with `scan_index` equal to a date-time object and int 
- [ ] Summary plots

**Note testers: please indicate what version of matplotlib you are using and OS**

### CODE REVIEW

**Review by carleyjmartin — APPROVED** [review]
Installed with `pip3 install git+https://github.com/superdarn/pydarn@release/v2.1.1`, no issues installing.

matplotlib version: 3.4.2
MacOS Catalina

 - [x] RTP testing
 `a = pydarn.RTP.plot_range_time(fitacf_data, beam_num=5, coords=pydarn.Coords.RANGE_GATE, round_start=False)`
and `round_start=True`
No issues, no unexpected user warnings
 - [x] time series with a vector parameter
 `a = pydarn.RTP.plot_time_series(fitacf_data, beam_num=3, parameter='v', gate=40)`
No issues, two user warnings:
```/Users/carley/Documents/testing_code/venv-patchtest/lib/python3.7/site-packages/pydarn/plotting/rtp.py: 712: UserWarning: Warning: converting a masked element to nan.
/Users/carley/Documents/testing_code/venv-patchtest/lib/python3.7/site-packages/numpy/ma/core.py: 2830: UserWarning: Warning: converting a masked element to nan.
/Users/carley/Documents/testing_code/venv-patchtest/lib/python3.7/site-packages/pydarn/plotting/rtp.py: 727: UserWarning: color is redundantly defined by the 'color' keyword argument and the fmt string "k" (-> color=(0.0, 0.0, 0.0, 1)). The keyword argument will take precedence.
```
 - [x] Fan plot testing with scan_index equal to a date-time object and int
 Tested with various radars and scan_index inputs, no issues, no unexpected warnings. Also tested with grid plots and various other keywords, with no issues. 
 - [x] Summary plots
 Tested with various radars and True and False for round-time, no issues, no unexpected warnings.

**Comment by Shirling-VT** [comment]
Installed with pip3 install git+https://github.com/superdarn/pydarn@release/v2.1.1, no issues installing.

matplotlib version: 3.3.4
MacOS Catalina

import matplotlib.pyplot as plt
from datetime import datetime
import pydarn

All the tests work good when I use this cly radar fitacf data file: 
file = '/Users/xueling/data/superdarn/2015/fitacf/cly/20150308.1400.03.cly.fitacf.bz2'
fitacf_data = pydarn.SuperDARNRead().read_dmap(file)

#########RTP test#########################
a = pydarn.RTP.plot_range_time(fitacf_data, beam_num=5, coords=pydarn.Coords.RANGE_GATE, round_start=False)
plt.show()

#############Vector paramter time series plot############3
a = pydarn.RTP.plot_time_series(fitacf_data, beam_num=3, parameter='v', gate=20)
plt.show()

#########################Summary plot test########################
a = pydarn.RTP.plot_summary(fitacf_data, beam_num=5, groundscatter=True)
plt.show()
a = pydarn.RTP.plot_summary(fitacf_data, beam_num=5, groundscatter=False)
plt.show()

####################Fan plot testing with scan_index equal to a date-time object and int#########
time = datetime(2015,3,8,15,32)
fanplot = pydarn.Fan.plot_fan(fitacf_data, scan_index=time,
                    colorbar_label='Velocity [m/s]',zmin=-1000, zmax=1000, lowlat=50, groundscatter=True)
plt.show()

fanplot = pydarn.Fan.plot_fan(fitacf_data, scan_index=1,
                    colorbar_label='Velocity [m/s]',zmin=-1000, zmax=1000, lowlat=50, groundscatter=True)
plt.show()

But when I change it to another data file, there are some issues which may be related to the data itself.
file = '/Users/xueling/data/superdarn/2015/fitacf/pyk/20150308.1401.00.pyk.fitacf.bz2'
fitacf_data = pydarn.SuperDARNRead().read_dmap(file)

I reported this issue before in pr #166 and not sure why it's showing up again. As I mentioned before, this may be due to the data file itself, but I still want to bring it up just in case.
1. For the fan plot with datatime and int as an input to scan_index, it won't work for this pky fitacf_data.
###########testing codes################
file = '/Users/xueling/data/superdarn/2015/fitacf/pyk/20150308.1401.00.pyk.fitacf.bz2'
fitacf_data = pydarn.SuperDARNRead().read_dmap(file)

time = datetime(2015,3,8,15,32)
fanplot = pydarn.Fan.plot_fan(fitacf_data, scan_index=time,
                    colorbar_label='Velocity [m/s]',zmin=-1000, zmax=1000, lowlat=50, groundscatter=True)
plt.show()

image

fanplot = pydarn.Fan.plot_fan(fitacf_data, scan_index=1,
                    colorbar_label='Velocity [m/s]',zmin=-1000, zmax=1000, lowlat=50, groundscatter=True)
plt.show()
image

2. The summary, RTP, and time series plots works fine in other beams except in Beam 5, which is really strange. The RTP plot example is shown below:
#########RTP test#########################
file = '/Users/xueling/data/superdarn/2015/fitacf/pyk/20150308.1401.00.pyk.fitacf.bz2'
fitacf_data = pydarn.SuperDARNRead().read_dmap(file)
a = pydarn.RTP.plot_range_time(fitacf_data, beam_num=5, coords=pydarn.Coords.RANGE_GATE, round_start=False)
plt.show()
image

I also tested in another radar operating in the same fast stereo mode (153) on the same date, and didn't find such issue. I haven't gotten time to test on more radars and dates yet. If nobody finds the same issue, I'll approve it as well.

**Comment by carleyjmartin** [comment]
@Shirling-VT 
Thanks for testing! 
I'm not sure if I explained it in the issue or not, but for some reason the data for that time period gives a weird pattern in the file for the scan flag value (0 if not a new scan, 1 if a new scan has started) It reads something like 1,1,0,0,0,0...0,1,1,0,0,... so for each scan our code picks out beam 0 (what you're seeing in the fan plots above) and then starts a new scan on beams 1 - 15 and 15 back to 1. 
For this reason I assumed that this data, if the scan intended to be this way, was not suitable for plotting on fan plots as it goes back over itself. 
I also noticed this didn't happen for other 153 mode data, so I'm unsure what it is about some 153 mode data that means the scan flag is done in this way?
Unfortunately, I don't think anyone was planning to incorporate handling individual scan modes into the fan plotting code. However, coming soon is `plot_beam` which I believe will be used to plot single individual beams, from which you can build a fan plot from what ever data you desire, and will solve the edge cases for plotting.

I think I recommended adding a warning to say not all scan modes are appropriate to view on fan plots, but I don't know if that materialized because I didn't do it?

I do not use RST, but would it be possible for someone to plot this data using another software, I assume we handle the scan flag value the same way to plot?

I can look into the RTP issue with beam 5 on that date, but I worry that the plotting code is working and plotting whatever data is there, so I will tentatively say (without actually looking into it yet) that the data is just weird for that day?

**Comment by Shirling-VT** [comment]
@carleyjmartin Thanks for the response. I apologize if I missed your previous explanation. I don't use RST either. But taking a look at the RTP and fan plot from the VT SuperDARN website for this radar on the same date (http://vt.superdarn.org/tiki-index.php?page=DaViT+RTP; http://vt.superdarn.org/tiki-index.php?page=DaViT+Multi+Scan+Plot), they all look normal to me. Not sure if the logic is the same between the davit IDL code running behind the VT SuperDARN website and pydarn/RST. It is not possible but very challenging to test on all radars and operational modes. Hopefully the current logic works for most of them.

**Comment by carleyjmartin** [comment]
@Shirling-VT 
Just to keep you in the loop! Dan is trying out the IDL davit code on this specific time to pinpoint what the differences are in making the fan plots between the two libraries. The only other thing I can think of is that the fitacf files that we use to plot here, and the files davit uses to plot through the VT website are slightly different? Dan will find out anyway!

**Comment by mts299** [comment]
@Shirling-VT Looks like you found a weird case I am going to make an issue on this and look into it. 1. might be the data 2. might be pyDARN but not sure if we should solve it for this patch release as its really minor if it is pyDARN. 

What do you think?

**Comment by carleyjmartin** [comment]
I've made the issue #182 - just so we have a single place to go have the discussion at :D

**Comment by Shirling-VT** [comment]
@mts299 I have no problem leaving this issue to the next release. Looks like it might need some effort to solve this problem as I pointed out in #182 .

**Comment by mts299** [comment]
Given the mess, I made with `develop` to this PR and forgetting we have `rpos` code in it. I am going to close this PR and make a minor release after I fix the issues in `develop` that `pytest` is now finding with this branch.

**Pull request closed without merging**
