### PR TITLE
Cleaning up pyDARN

### PR DESCRIPTION
**Pull request by mts299**
I went into the test section and cleaned up some old files as added some other SuperDARN related files to the gitignore. 

@mardet987 do you want to try and clone this branch and see if you can get it to work at Clyde?

### CODE REVIEW

**Comment by mardet987** [comment]
Hey so I am still struggling with downloading at Clyde River. It's got to be in combination with the internet connection there too, but I did do some digging and found this:

83M	./.git/objects/pack

which led me to this link:
[](https://stackoverflow.com/questions/1029969/why-is-my-git-repository-so-big)
so I was wondering if we could consider the git gc command to do some cleanup, unless you've done this already?

**Comment by mts299** [comment]
No, I haven't thank you for looking into this. I have ran the `git gc` command suggested on the link. 

Is it better now?

**Comment by mardet987** [comment]
Thanks, it's the same size though. So I just did a bit more digging and found more info here: [https://confluence.atlassian.com/bitbucket/maintaining-a-git-repository-321848291.html](https://confluence.atlassian.com/bitbucket/maintaining-a-git-repository-321848291.html)

I used the script that they provided and found this: 

> marci@linux-t3oz:~/pydarn-test/pydarn> ./git_find_big.sh 
All sizes are in kB's. The pack column is the size of the object, compressed, inside the pack file.
size   pack   SHA                                       location
95154  56316  5e6fcde743a9fa1c207b2bcdfe70a7ee0d2b2777  test/dmap_tests/testfiles/20160301.C0.sas.fitacf
30542  15520  2a29d6a0bc74ed5f363b44f4c722b1a9a438a781  test/dmap_tests/testfiles/20180623.map
11904  5785   abe6f7b21f493934aedcf683062e5ffd84becee3  test/dmap_tests/testfiles/20160316.1945.01.rkn.iqdat
11012  3130   1d6fedc740b25a5383698ad244b364a12eab2006  test/dmap_tests/testfiles/20110214.map
387    382    1bcac2df6ff80b8d3f466957ac6616e15ba1dc4f  docs/imgs/summary_clyb2_boundaries.png
381    377    87f5fc4bd6944d675dfa9bdbd03eb900499b8256  docs/imgs/summary_clyb2.png
308    301    b0f617fa81191ea19539a0598e896c99e21ff050  pydarn_range_time_plots.png
251    229    a1e0b94f941017df6cbcd4c66bb20981765699df  docs/imgs/rtp_clyb7_3.png
250    228    24cee2285c6e38f396115b3923f5750f918a289b  docs/imgs/rtp_clyb7_2.png
238    207    d3ed55edd7cb3d81114611018ea85272a58d4ae0  docs/imgs/cpid_eg.png

so I think there is a fitacf file, map file, and iqdat file on one of the pydarn branches that maybe we could delete, remove reflog history (not sure how to do this but can look up more) and rerun the git gc garbage collector?

**Comment by mts299** [comment]
Okay, well I removed the rawacf file on this branch, so maybe we merge this branch in then merge it to the other branches it should get rid of that file? Then on develop I can do some more cleaning and searching.

**Comment by mardet987** [comment]
sounds good I will merge

**Pull request merged**
