### PR TITLE
Boxcar filter

### PR DESCRIPTION
**Pull request by shibaji7**
# Median Filtering

**Name**: *Median Filter*

**module**:  *boxcar_filter.py* 

**package**: *utils*

## Scope

*What will the feature do?*
- Reduce salt and paper noise in the fitacf type dataset. 

## Description

*Please provide a description of the new feature and if will improve or solve a problem.*

### pyDARN Checklist 

-  [x] Does this fit within pyDARN's scope? 
-  [ ] Is this a minor change i.e., new small utility function?
-  [x] Is this a major change i.e., new plotting function?
-  [x] Do you need help developing it? 
-  [ ] Have you created a pyDARN GitHub [project](https://github.com/SuperDARN/pydarn/projects) to show the tasks needed to be done? 

### Development help

- [x] developer help with design and integration of code
- [ ] scientific help with ensuring what you develop is scientifically correct/accurate
- [x] project management to help organize what steps need to be taken to make this possible 

## User Interface 

*pydarn.boxcar_filter(start_date=None, end_date=None, data=None, weight=0.7, kernel=None)*

## Extra Notes

*Please provide any other details about this feature*
- *Maimaiti, M., Ruohoniemi, J. M., Baker, J. B. H., & Ribeiro, A. J. (2018). Statistical study of nightside quiet time midlatitude ionospheric convection. Journal of Geophysical Research: Space Physics, 123, 2228– 2240. https://doi.org/10.1002/2017JA024903*
- *https://github.com/shibaji7/AMGeO-SD/blob/master/sd/boxcar_filter.py*

### CODE REVIEW

**Comment by mts299** [comment]
@shibaji7 Did you want to add the actual code in?

**Comment by shibaji7** [comment]
> 

Yes, here is the link https://github.com/SuperDARN/pydarn/blob/boxcar-filter/pydarn/utils/boxcar_filter.py

**Comment by mts299** [comment]
@shibaji7 if you look at the file its a bunch of authorship info but no code... 

```
#!/usr/bin/env python

"""boxcar_filter.py: Module is dedicated to run 3X3X3 boxcar filtering."""

__author__ = "Chakraborty, S."
__credits__ = []
__version__ = "1.0."
__maintainer__ = "Chakraborty, S."
__email__ = "shibaji7@vt.edu"
__status__ = "Research"
__copyright__ = ""
__license__ = ""
```

This is all I see right now

**Comment by mts299** [comment]
@shibaji7 let me know when you get it in :)

**Comment by carleyjmartin** [comment]
Hi @shibaji7, I'm really struggling to get this to work when reading in dmap data, do you have an example of this working with data? I'm assuming you might have some peripheral piece of code that makes the data into the correct format before piping it in, like compile_data, but compile_data gives me errors as `self._b` doesn't exist in this code :/

**Comment by shibaji7** [comment]
> e_data gives me errors as `self._b` doesn't e

@carleyjmartin Thank you for taking this, I'm busy with a review panel this and next week. I'll take a look as soon as I get some time.

**Comment by shibaji7** [comment]
> > e_data gives me errors as `self._b` doesn't e
> 
> @carleyjmartin Thank you for taking this, I'm busy with a review panel this and next week. I'll take a look as soon as I get some time.

I have modified the codebase and also uploaded a example testcase under test/ folder for your reference. You need a .bz2 file to test it. I used this file '/sd-data/2015/fitacf/sas/20150317.0000.03.sas.fitacf.bz2'.

**Comment by carleyjmartin** [comment]
Hello! It was easier for me to add this code to an up to date branch than pull the changes here as the rest of this branch is still back at v2.1, so I've made a new PR at #296 with all the code and things required for integrating. I'll close this for now and we can continue discussion over there :)

**Pull request closed without merging**
